# Análisis de Datos sobre DS de Ganadores de Oscars - Parte 1.

### DS Utilizado: https://www.kaggle.com/fmejia21/demographics-of-academy-awards-oscars-winners

![No se cargo la imagen correctamente](data/Oscars.jpg "Imagen Oscars")

## 1- Lectura, estructura de DF y Data Types

#### Importamos las librerias

In [1]:
import pandas as pd #To provide high-performance, easy-to-use data structures and data analysis tools for the Python programming
import numpy as np #To add support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
import seaborn as sns
import matplotlib.pyplot as plt # Plotting library for the Python programming language and its numerical mathematics extension NumPy.
%matplotlib inline
# to have the output of plotting commands displayed inline within frontends like the Jupyter notebook, directly below the code cell that produced it. The resulting plots will then also be stored in the notebook document.

#### Lectura del archivo

In [6]:
#Como la data está en CSV lo leeremos usando la funcion readl_csv() que nos permite
#parsear y cargar la data dentro de un DATAFRAME facilmente.
#Luego con la función head() vemos lo que leimos. Y le indicamos que queremos ver 5 columnas.
oscars_demographics = pd.read_csv('data/Oscars-demographics-DFE.csv', encoding='latin-1')
oscars_demographics.head(5)

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,award,biourl,birthplace_gold,date_of_birth_gold,movie,person,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
0,670454353,False,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,Two Arabian Knights,Lewis Milestone,NaN,NaN,NaN,NaN
1,670454354,False,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1.0,2-Feb-1886,1.0,White,...,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,The Divine Lady,Frank Lloyd,NaN,NaN,NaN,NaN
2,670454355,False,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,All Quiet on the Western Front,Lewis Milestone,NaN,NaN,NaN,NaN
3,670454356,False,finalized,3,2/10/15 2:04,"Chicago, Il",1.0,23-Feb-1899,1.0,White,...,Best Director,http://www.nndb.com/people/544/000041421/,NaN,NaN,Skippy,Norman Taurog,NaN,NaN,NaN,NaN
4,670454357,False,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1.0,23-Apr-1894,1.0,White,...,Best Director,http://www.nndb.com/people/292/000044160/,NaN,NaN,Bad Girl,Frank Borzage,NaN,NaN,NaN,NaN

In [8]:
#Analizamos el DS y vemos que es un DS de personas que ganaron el oscar en alguna oportunidad: hay actores y actrices y tambien directores.
#AHora sacamos los datos relevantes... solo las columnas que nos interesan:
oscars_short = pd.read_csv('data/Oscars-demographics-DFE.csv',
                        encoding='latin-1',
                        usecols = ['birthplace', 'date_of_birth','race_ethnicity','religion','sexual_orientation','year_of_award','award','movie','person'])
oscars_short.head(5)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

In [9]:
#AHora vamos a querer ver info especifica del DF:
oscars_demographics.info()  #Utilizamos el 1er DF, el que tenia todas las columnas.
#Nos da el detalle de la estructura del DF:
    #En non-null vemos que la mayoria tiene 441 valores NO nulos... pero por ej. birthplace_gold tiene solo 9, el resto son NaN.  
    #Dtype: es el tipo de dato que asoció automáticamente Pandas al hacer read_csv(). Si tan solo 1 valor no machea para ese tipo de dato va a elegir otro el tipo: 'Object' (tipo de dato que elige si NO machea con ningñun otro más)
            #Object son strings, la mayoría machean con ese tipo de dato.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 27 columns):
_unit_id                         441 non-null int64
_golden                          441 non-null bool
_unit_state                      441 non-null object
_trusted_judgments               441 non-null int64
_last_judgment_at                416 non-null object
birthplace                       441 non-null object
birthplace:confidence            441 non-null float64
date_of_birth                    441 non-null object
date_of_birth:confidence         441 non-null float64
race_ethnicity                   441 non-null object
race_ethnicity:confidence        441 non-null float64
religion                         441 non-null object
religion:confidence              441 non-null float64
sexual_orientation               441 non-null object
sexual_orientation:confidence    441 non-null float64
year_of_award                    441 non-null int64
year_of_award:confidence         441 non-null float64
award                            441 non-null object
biourl                           441 non-null object
birthplace_gold                  9 non-null object
date_of_birth_gold               8 non-null object
movie                            441 non-null object
person                           441 non-null object
race_ethnicity_gold              2 non-null object
religion_gold                    10 non-null object
sexual_orientation_gold          3 non-null object
year_of_award_gold               11 non-null float64
dtypes: bool(1), float64(7), int64(3), object(16)
memory usage: 90.1+ KB

In [10]:
#Para saber datos estadisticos del dataset hacemos esto:
oscars_demographics.describe() 
#De esta manera tenemos estadisticas sobre cada una de las columnas NUMERICAS (las otras columnas NO)
#El '25%'' es en qué valor se CENTRA el 25%.

,_unit_id,_trusted_judgments,birthplace:confidence,date_of_birth:confidence,race_ethnicity:confidence,religion:confidence,sexual_orientation:confidence,year_of_award,year_of_award:confidence,year_of_award_gold
count,4.410000e+02,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,11.000000
mean,6.704825e+08,7.637188,0.995259,0.996607,0.999130,0.989373,0.992390,1973.165533,0.990082,1977.363636
std,1.139974e+05,19.015541,0.038917,0.032060,0.016438,0.065610,0.049458,24.030895,0.059177,21.592928
min,6.704544e+08,3.000000,0.657100,0.656200,0.657100,0.333300,0.657100,1927.000000,0.333300,1942.000000
25%,6.704545e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1953.000000,1.000000,1964.000000
50%,6.704546e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1973.000000,1.000000,1977.000000
75%,6.704547e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1994.000000,1.000000,1997.000000
max,6.709729e+08,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,2006.000000

In [188]:
#Ahora vamos a ver la ESTRUCTURA del DF que explicamos en el apunte... (indice de datos, indice de columnas y la data) para poder analizarlas por separado.
oscars_index=oscars_demographics.index #asi obtenemos el ùndice (en este caso es un RangeIndex ya que no tenemos seteado ninguna columna como ìndice. Rageindex son valores consecutivos numericos desde 0)
oscars_columns=oscars_demographics.columns  #para obtener las columnas. Es una SERIE con los nombres de todas las columnas.
oscars_data=oscars_demographics.values #para obtener la data. La operacion que nos devuelve obtiene tooodos los datos y los pone en un array. 

#Abajo mostramos estos 3:

In [189]:
oscars_index

RangeIndex(start=0, stop=441, step=1)

In [190]:
oscars_columns

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'birthplace', 'birthplace:confidence',
       'date_of_birth', 'date_of_birth:confidence', 'race_ethnicity',
       'race_ethnicity:confidence', 'religion', 'religion:confidence',
       'sexual_orientation', 'sexual_orientation:confidence', 'year_of_award',
       'year_of_award:confidence', 'award', 'biourl', 'birthplace_gold',
       'date_of_birth_gold', 'movie', 'person', 'race_ethnicity_gold',
       'religion_gold', 'sexual_orientation_gold', 'year_of_award_gold'],
      dtype='object')

In [191]:
oscars_data

array([[670454353, False, 'finalized', ..., nan, nan, nan],
       [670454354, False, 'finalized', ..., nan, nan, nan],
       [670454355, False, 'finalized', ..., nan, nan, nan],
       ...,
       [670964912, False, 'finalized', ..., nan, nan, nan],
       [670964956, False, 'finalized', ..., nan, nan, nan],
       [670972898, False, 'finalized', ..., nan, nan, nan]], dtype=object)

In [192]:
#AHora vamos a ver el tipo de datos de cada estructura:

type(oscars_index) #Vemos que tiene un tipo de dato RangeIndex.

pandas.core.indexes.range.RangeIndex

In [193]:
type(oscars_columns) #Tipo de dato Index.

pandas.core.indexes.base.Index

In [194]:
type(oscars_data) #Tipo de dato Array.

numpy.ndarray

In [195]:
#AHora vemos los tipos de dato de cada columna de oscars_demographics(Que anteriormente vimos igualmente con oscars_demographics.info() )
oscars_demographics.dtypes

_unit_id                           int64
_golden                             bool
_unit_state                       object
_trusted_judgments                 int64
_last_judgment_at                 object
birthplace                        object
birthplace:confidence            float64
date_of_birth                     object
date_of_birth:confidence         float64
race_ethnicity                    object
race_ethnicity:confidence        float64
religion                          object
religion:confidence              float64
sexual_orientation                object
sexual_orientation:confidence    float64
year_of_award                      int64
year_of_award:confidence         float64
award                             object
biourl                            object
birthplace_gold                   object
date_of_birth_gold                object
movie                             object
person                            object
race_ethnicity_gold               object
religion_gold                     object
sexual_orientation_gold           object
year_of_award_gold               float64
dtype: object

In [196]:
#Con value_counts vamos a contar todas las ocurrencias de los distintos valores que aparecen en una serie:
oscars_demographics.dtypes.value_counts()
#De esta manera vemos la cantidad de tipos de datos que tenemos (tenemos 16 objects, 7 floats, 3 inst y 1 bool)

object     16
float64     7
int64       3
bool        1
dtype: int64

## 2- Manejo de Series y estadìsticas sobre los datos.

In [197]:
#Anteriormente mencionamos ya que cada columna es una SERIE.
#Una SERIE es un dato de una sola dimensión compuesto de solo un indice y su data. 
#Podemos seleccionar una columna utilizando el index operator  o utilizando la notación "dot"

#Ahora vamos a utilizar el index operator para tomar todos los nombres de las personas (columna 'person'):
oscars_demographics['person'] #esto es una SERIE

0      Lewis Milestone
1          Frank Lloyd
2      Lewis Milestone
3        Norman Taurog
4        Frank Borzage
            ...
436       Rachel Weisz
437        Danny Boyle
438      Jason Robards
439       James Coburn
440        John Huston
Name: person, Length: 441, dtype: object

In [198]:
#Hacemos lo mismo que arriba pero utilizando la notación "dot":
oscars_demographics.person

0      Lewis Milestone
1          Frank Lloyd
2      Lewis Milestone
3        Norman Taurog
4        Frank Borzage
            ...
436       Rachel Weisz
437        Danny Boyle
438      Jason Robards
439       James Coburn
440        John Huston
Name: person, Length: 441, dtype: object

In [199]:
#Le hacemos un type a la columna person para ver que es del tipo serie:
columnaPerson = oscars_demographics['person']
type(columnaPerson)

pandas.core.series.Series

In [200]:
#AHora queremos transformar esto en un DATAFRAME:
columnaPersonADF = oscars_demographics['person'].to_frame()
type(columnaPersonADF)

#Esto lo hacemos ya que hay ciertas operaciones que se pueden realizar en series
#y ciertas operaciones que se pueden realizar sobre DF's.

pandas.core.frame.DataFrame

In [201]:
#AHora le hacemos un info al DF para verlo como una estructura con una ùnica columna:
columnaPersonADF.info()
#columnaPerson.info()  #a una serie NO podemos aplicarle esto por ej.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   person  441 non-null    object
dtypes: object(1)
memory usage: 3.6+ KB

In [202]:
#Para listar los métodos que aplican sobre series:
Series_Methods = set(dir(pd.Series))
len(Series_Methods)

434

In [203]:
Series_Methods

{'T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_convert_dtypes',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_type',
 '_find_valid_index',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iget_item_cache',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_ndarray_values',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'bool',
 'cat',
 'clip',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dt',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sparse',
 'squeeze',
 'std',
 'str',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'tolist',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs'}

In [204]:
#Para listar los métodos que aplican sobre DFs:
DF_Methods = set(dir(pd.DataFrame))
len(DF_Methods)

431

In [205]:
DF_Methods

{'T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_frame',
 '_combine_match_index',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_type',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sparse',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs'}

In [206]:
#Como ejemplo vamos a seleccionar 2 columnas con 2 tipos de datos distintos
#para ver asi que las operaciones con distintos datos pueden dar resultados distintos.

#Seleccionamos la pelicula y luego el año:
oscars_movie = oscars_demographics['movie'] #es un object.
oscars_years = oscars_demographics['year_of_award'] #es un int

In [207]:
oscars_movie.head(5) #Serie con los nombres. (NO es un DF)

0               Two Arabian Knights
1                   The Divine Lady
2    All Quiet on the Western Front
3                            Skippy
4                          Bad Girl
Name: movie, dtype: object

In [208]:
oscars_years.head(5) #Serie con los años. (NO es un DF)

0    1927
1    1930
2    1931
3    1932
4    1933
Name: year_of_award, dtype: int64

In [209]:
#Sobre una serie podemos hacer varios Value_Counts():

In [210]:
oscars_movie.value_counts() #Para ver las ocurrencias de cada valor (Million DOllar Baby vemos que tiene 5 ocurrencias)

Million Dollar Baby      5
Network                  4
West Side Story          4
It Happened One Night    3
Gone with the Wind       3
                        ..
Ordinary People          1
The Killing Fields       1
Butterfield 8            1
Cavalcade                1
Airport                  1
Name: movie, Length: 336, dtype: int64

In [211]:
#Ponemos el normalize=True para obtener asi el
#porcentual, osea el volumen relativo de cada una de las peliculas
oscars_movie.value_counts(normalize=True)
#Nos muestra para cada pelicula los porcentajes de ocurrencia respecto a todas ahora.
#Tooodos los valores numericos que vemos abajo (0.011338, 0.0009070 y todas las demás) SUMAN 1... entonces 
#el 0.011338 es la participación que tuvo la 1er peli con respecto a las demás pelis (el 100%)

Million Dollar Baby      0.011338
Network                  0.009070
West Side Story          0.009070
It Happened One Night    0.006803
Gone with the Wind       0.006803
                           ...
Ordinary People          0.002268
The Killing Fields       0.002268
Butterfield 8            0.002268
Cavalcade                0.002268
Airport                  0.002268
Name: movie, Length: 336, dtype: float64

In [212]:
oscars_years.value_counts()  #AHora hacemos lo mismo para los años que son variables numéricas.
#Y obtenemos la distribución.. para 1969 son 8, 2005 son 7, etc.
#Obviamente este DS NO esta completo ya que en 1933 por ej. hay 1 solo.

1969    8
2005    7
1961    7
1999    7
2009    7
       ..
1932    3
1931    3
1929    2
1933    1
1927    1
Name: year_of_award, Length: 87, dtype: int64

In [213]:
oscars_years.value_counts(normalize=True)
#Me dice nuevamente en porcentaje cuantas veces aparecen los años.

1969    0.018141
2005    0.015873
1961    0.015873
1999    0.015873
2009    0.015873
          ...
1932    0.006803
1931    0.006803
1929    0.004535
1933    0.002268
1927    0.002268
Name: year_of_award, Length: 87, dtype: float64

In [214]:
#Usamos size, shape y len para contar el nùmero de elementos en DF:
type(oscars_demographics)

pandas.core.frame.DataFrame

In [215]:
oscars_demographics.size #Nos muestra la cantidad de elementos que tenemos (filas y columnas, TODO)

11907

In [216]:
oscars_demographics.shape #(Filas y columnas que tenemos)

(441, 27)

In [217]:
len(oscars_demographics) #Cantidad de filas que tenemos

441

In [218]:
oscars_demographics.count() #Vemos los valores asociados a cada columna

_unit_id                         441
_golden                          441
_unit_state                      441
_trusted_judgments               441
_last_judgment_at                416
birthplace                       441
birthplace:confidence            441
date_of_birth                    441
date_of_birth:confidence         441
race_ethnicity                   441
race_ethnicity:confidence        441
religion                         441
religion:confidence              441
sexual_orientation               441
sexual_orientation:confidence    441
year_of_award                    441
year_of_award:confidence         441
award                            441
biourl                           441
birthplace_gold                    9
date_of_birth_gold                 8
movie                            441
person                           441
race_ethnicity_gold                2
religion_gold                     10
sexual_orientation_gold            3
year_of_award_gold                11
dtype: int64

In [219]:
#Ahora hacemos lo mismo (Usamos size, shape y len para contar el nùmero de elementos)
#pero ahora no es un DF, sino una Serie:
Serie_Date_Birth_Gold = oscars_demographics['date_of_birth_gold']
type(Serie_Date_Birth_Gold)

pandas.core.series.Series

In [220]:
Serie_Date_Birth_Gold.size #Vemos el TOTAL de datos (sean o no Nans)

441

In [221]:
Serie_Date_Birth_Gold.count() #Vemos que de los 441 que tiene de longitud solo 8 valores son distintos de null. 
#Anteriormente hicimos count() solo para el DF y como vimos nos devuelve las cantidades PARA CADA COLUMNA; aca con Series solo para esa columna.

8

In [222]:
Serie_Date_Birth_Gold.isnull() #Nos devuelve un valor booleano asociado a cada una de las posiciones indicando si es V o F que es nulo 
#(vemos que la mayoria son nullos por los T) --> son una SERIE de valores booleanos

0      True
1      True
2      True
3      True
4      True
       ...
436    True
437    True
438    True
439    True
440    True
Name: date_of_birth_gold, Length: 441, dtype: bool

In [223]:
Serie_Date_Birth_Gold.hasnans #SImplemente nos dice si existe algun Nan (null) dentro de la columna. SI tenemos solo 1 nos devuelve True.

True

In [224]:
#Aca como todos tienen valores nos devuelve False.

Serie_Persons = oscars_demographics['person']
Serie_Persons.hasnans

False

In [225]:
Serie_Date_Birth_Gold  #Imprimiendo asi nos devuelve una Serie con los valores de la columna (la mayoria 'NaN')

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
436    NaN
437    NaN
438    NaN
439    NaN
440    NaN
Name: date_of_birth_gold, Length: 441, dtype: object

In [226]:
#AHora vamos a hacer algo con los valores que NO estan definidos...
#Vamos a hacer un FIlling Nan... así para todos los valores NaN le vamos a poner el valor 'None'
Serie_Date_Birth_Gold_Fill_NaNs = Serie_Date_Birth_Gold.fillna('None')

In [227]:
Serie_Date_Birth_Gold_Fill_NaNs #Lo imprimimos y vemos que los cambio por None:

0      None
1      None
2      None
3      None
4      None
       ...
436    None
437    None
438    None
439    None
440    None
Name: date_of_birth_gold, Length: 441, dtype: object

In [228]:
Serie_Date_Birth_Gold_Fill_NaNs.hasnans #VEmos que NO tiene Nans

False

In [229]:
Serie_Date_Birth_Gold_Fill_NaNs.count() #Antes nos tiraba 8, ahora nos tira todos ya que los rellenamos.

441

In [230]:
Serie_Date_Birth_Gold_Fill_NaNs.size #Y bueno aca nos tira nuevamente todos porque no considera los Nans.

441

In [231]:
#Ahora enves de rellenar vamos a Dropearlos/Removerlos:
Serie_Date_Birth_Gold_Nans_Dropped=Serie_Date_Birth_Gold.dropna()

In [232]:
Serie_Date_Birth_Gold_Nans_Dropped  #Solo tenemos los que NO eran NaN.

21      5-Aug-06
33     22-Jun-06
152     9-Jul-56
205    16-Jun-07
263    16-Jul-11
280    27-Feb-30
377    31-Oct-27
411    11-Dec-67
Name: date_of_birth_gold, dtype: object

In [233]:
Serie_Date_Birth_Gold_Nans_Dropped.count() #Nos da solo los que no tenian Nan... en este caso igual ninguno tienen Nan porque esos los eliminamos directamente.

8

In [234]:
Serie_Date_Birth_Gold_Nans_Dropped.size #Nos tira TODOS los valores (igual tenemos 8, el resto los volamos)

8

#### Ahora vamos a ver métodos básicos de estadística:  min, max, mean, median, std, sum y describe.

In [240]:
#Anteriormente vimos que aplicando describe() sobre el DF te aplicaba todos los métodos de estadisticas para las variables NUMÉRICAS del mismo
#Tambien podemos correr metricas de estadistica especificando las columnas si no lo queremos hacer sobre todo:
#Saber... _trusted_judgments es una columna de nuestro DS.

min_columna_trusted_j=oscars_demographics._trusted_judgments.min()
max_columna_trusted_j=oscars_demographics._trusted_judgments.max()
mean_columna_trusted_j=oscars_demographics._trusted_judgments.mean()
median_columna_trusted_j=oscars_demographics._trusted_judgments.median()
std_columna_trusted_j=oscars_demographics._trusted_judgments.std()
sum_columna_trusted_j=oscars_demographics._trusted_judgments.sum()

#Ahora imprimimos todos estos como una lista (separandolos por ,):
min_columna_trusted_j, max_columna_trusted_j, mean_columna_trusted_j, median_columna_trusted_j, std_columna_trusted_j, sum_columna_trusted_j

(3, 95, 7.63718820861678, 3.0, 19.015540899806783, 3368)

In [241]:
#Pero utilizando describe nos corre todas las estadisticas de una (Sobre la columna que le indicamos):
oscars_demographics._trusted_judgments.describe()

count    441.000000
mean       7.637188
std       19.015541
min        3.000000
25%        3.000000
50%        3.000000
75%        3.000000
max       95.000000
Name: _trusted_judgments, dtype: float64

In [242]:
#SI hacemos lo mismo sobre una columna OBJECT (por ej. movie)
#los valores van a ser distintos (que que NO podemos hacer un promedio de Strings)
#Solo nos dice cuantos valores totales y únicos tenemos, el valor más comun (top) y su frecuencia.
oscars_demographics.movie.describe()

count                     441
unique                    336
top       Million Dollar Baby
freq                        5
Name: movie, dtype: object

In [243]:
#SI corremos el describe() sobre todo el DF nos va a tirar el resultado
#sobre todas las columnas que sean NUMERICAS (no va a tener en cuenta los objecs acá directamente)
oscars_demographics.describe()

,_unit_id,_trusted_judgments,birthplace:confidence,date_of_birth:confidence,race_ethnicity:confidence,religion:confidence,sexual_orientation:confidence,year_of_award,year_of_award:confidence,year_of_award_gold
count,4.410000e+02,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,11.000000
mean,6.704825e+08,7.637188,0.995259,0.996607,0.999130,0.989373,0.992390,1973.165533,0.990082,1977.363636
std,1.139974e+05,19.015541,0.038917,0.032060,0.016438,0.065610,0.049458,24.030895,0.059177,21.592928
min,6.704544e+08,3.000000,0.657100,0.656200,0.657100,0.333300,0.657100,1927.000000,0.333300,1942.000000
25%,6.704545e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1953.000000,1.000000,1964.000000
50%,6.704546e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1973.000000,1.000000,1977.000000
75%,6.704547e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1994.000000,1.000000,1997.000000
max,6.709729e+08,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,2006.000000

## 3-Operaciones sobre series

In [246]:
#COmo dijismos antes.. cada columna de nuestro DF es una SERIE. 
#Nos quedamos con la columna _trusted_judgments... entonces tendremos una serie de valores asociados a esa columna:
oscars_demographics['_trusted_judgments']

0      3
1      3
2      3
3      3
4      3
      ..
436    3
437    3
438    3
439    3
440    3
Name: _trusted_judgments, Length: 441, dtype: int64

In [247]:
#Hacemos lo mismo que hicimos antes (calculamos la media, min y maximo de esa columa usnando los operadores que ya vimos):

min_columna_trusted_j=oscars_demographics['_trusted_judgments'].min()
max_columna_trusted_j=oscars_demographics['_trusted_judgments'].max()
mean_columna_trusted_j=oscars_demographics['_trusted_judgments'].mean()

#Y ahora imprimimos estos 3 resultados:
min_columna_trusted_j, max_columna_trusted_j, mean_columna_trusted_j

(3, 95, 7.63718820861678)

In [249]:
#Ahora vamos a ver los valores posibles... utilizando el value_counts() que aplica sobre series:
#Y vemos que el value 3 tiene 416 ocurrencias. Y los demás valores van bajando... 
#ya que esto está ordenado del valor más al menos frecuente.
oscars_demographics['_trusted_judgments'].value_counts()

3     416
91      5
87      3
86      3
84      2
76      2
75      2
95      1
92      1
90      1
89      1
85      1
82      1
81      1
62      1
Name: _trusted_judgments, dtype: int64

In [251]:
#Tambien podemos aplicar operaciones (al minumo le sumamos 1):
min_columna_trusted_j+1  #COmo min_columna_trusted_j era 3, le sumamos 1 y nos da 4.

4

In [254]:
#En cambio ahora si a la columna le sumamos 1 lo que vamos a obtener es 
#una serie que va a sumar 1 a cada valor de la columna (antes la mayorìa eran 3... ahora van a ser 4)
oscars_demographics['_trusted_judgments'] + 1

0      4
1      4
2      4
3      4
4      4
      ..
436    4
437    4
438    4
439    4
440    4
Name: _trusted_judgments, Length: 441, dtype: int64

In [255]:
#Tambien podemos aplicar multiplicación para cada uno de estos valores:
oscars_demographics['_trusted_judgments'] * 3

0      9
1      9
2      9
3      9
4      9
      ..
436    9
437    9
438    9
439    9
440    9
Name: _trusted_judgments, Length: 441, dtype: int64

In [258]:
#Anteriormente teniamos esto:
oscars_years = oscars_demographics['year_of_award'] #es un int
#Ahora vamos a ver cuales de estos son iguales a 1969:
(oscars_years == 1969).value_counts()
#Y nos tira que 8 son iguales.Y el 433 es para las ocurrencias que no son iguales a 1969.
#Comparamos una serie con un valor.. y lo que nos devuelve es otra serie de igual cantidad de elementos
#pero con valores booleanos, donde se ve si para cada elemento cumple o no la condición que le fijamos (que sea = a 1969)
#Por esto si hacemos un value count sobre esa serie obtenemos la cantidad de Falses y de True (y está ordenado del mas al menos frecuente: por esto primero el False con 433)

False    433
True       8
Name: year_of_award, dtype: int64

In [266]:
(oscars_years < 2014).value_counts() #Vemos que no esta muy actualizado, solo tiene 4 peliculas mayores a 2014.

True     437
False      4
Name: year_of_award, dtype: int64

In [267]:
#Entonces... operadores:
#Aritmeticos: +,-,/,//,%  
    #Aritmeticos equivalentes: add, sub, mul, div, floordiv, mod, pow
#De comparacion: <,>,<=,>=,==,!=
    #De comparacion equivalentes: it, gt, le, ge, eq, ne

In [269]:
#ENtonces hacemos lo mismo con el equivalente al == en comparacion:
oscars_years.eq(1969).value_counts()

False    433
True       8
Name: year_of_award, dtype: int64

In [277]:
#Los métodos tambien pueden encadenarse (para esto usamos el punto .)
oscars_demographics['year_of_award_gold'].isnull() 
#Primero asi, sin concatenar. A la serie oscars_demographics['year_of_award_gold'] le 
#aplicamos innull() que nos va a dar valores T o F en función si es null o no lo es.

0      True
1      True
2      True
3      True
4      True
       ...
436    True
437    True
438    True
439    True
440    True
Name: year_of_award_gold, Length: 441, dtype: bool

In [280]:
#Ahora concatenamos con sum() lo anterior:
oscars_demographics['year_of_award_gold'].isnull().sum()
#Lo que hace esto es contar los NULLs que tenemos en la columna.

430

In [282]:
#Ahora concatenamos con mean():
oscars_demographics['year_of_award_gold'].isnull().mean()
#Ahora vemos la media/porcentaje de valores NO definidos (nulls) en esa columna:
#En este caso el 97,5%... es null, BASTANTE.

0.9750566893424036

In [286]:
#Para splitear y poder escribir código debajo usamos la barra invertida (\)... para asi leer instrucciones de lineas muuuy largas
#La barra invertida (\) la hago con ALTGR + el botón de la izquierda debajo de escape.
oscars_demographics['year_of_award_gold'].isnull()\
                    .mean()
#SOlo visualmente lo separamos en 2 renglones para que no se haga largo.

0.9750566893424036

In [288]:
#Otra opcion para hacer lo mismo que con la barra invertida es
#METER TODO ENTRE PARENTESIS:
( oscars_demographics['year_of_award_gold'].isnull()
                    .mean() )

0.9750566893424036

## 4-Limpieza de dataset y manejo de indices

In [13]:
#Ahora vamos a hablar del manejo de Data Sets... como hacer una limpieza de los datos. 
#Vamos a LIMPIAR la data para prepararnos para el analisis:
    #1-Mantenemos las columnas que estamos interesados en usar.
    #2-Limpiamos valores null del dataset (o hacemos fill o los removemos)
    #3-Podemos convertir un tipo de dato en otro (por ej. year de float a INT)

#Entonces, empezamos
#1-Mantenemos las columnas que estamos interesados en usar.
oscars =  oscars_demographics[['birthplace','date_of_birth','race_ethnicity','religion','sexual_orientation','year_of_award','award','movie','person']]
oscars.head(5) #Mostramos los 5 primeros.

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

In [21]:
#2-Limpiamos valores null del dataset (o hacemos fill o los removemos)
print("Len Original:",len(oscars))  #Cantidad de registros que tenemos en el DF original. 
#Ahora aplicamos dropna... como ahora NO lo aplicamos sobre una columna en particular, sino que
#lo aplicamos en TODO el DF... va a verificar que no haya NINGUNA columna dentro del DF.
oscars.dropna(inplace=True) 
print("Len luego de dropear filas NaN:",len(oscars))  #Vemos que me dá 441 (IGUAL al original)
                    #Si me hubiera dado 440 es que mi DF seguramente tenía alguna FILA con todos valores en Nan.. en este caso no fue asi,
                    #Pero esto es recomendable hacerlo para asegurarse esto (que no tengamos filas con datos nulos).

Len Original: 441
Len luego de dropear filas NaN: 441

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [24]:
#Mostramos todas las columnas con el tipo asociado (este tipo de dato es automáticamente asignado al hacer el read; todavia no tocamos nada de esto)
oscars.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 441 entries, 0 to 440
Data columns (total 9 columns):
birthplace            441 non-null object
date_of_birth         441 non-null object
race_ethnicity        441 non-null object
religion              441 non-null object
sexual_orientation    441 non-null object
year_of_award         441 non-null int64
award                 441 non-null object
movie                 441 non-null object
person                441 non-null object
dtypes: int64(1), object(8)
memory usage: 34.5+ KB

In [25]:
#3-Podemos convertir un tipo de dato en otro (por ej. year de float a INT)
#Al parecer lo hacemos despues... VER CUANDO.

In [26]:
#Vamos a utilizar nuevamente los INDICES:
    #Indices de filas: proveen un label para cada fila. Si NO hay un indice explicito (uno que nosotros le digamos) entonces el indice
            #por defecto será el "RANGEINDEX" (osea el que vemos abajo en la "columna 0" que va 0,1,2,3,4, etc...)
            #Este RANGEINDEX asocia/asigna cada valor numérico a cada fila de nuestro DF.
    #Indices de columnas.
    
#Mostramos los Oscars para ver los RANGEINDEX:
oscars

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
11,"Pasadena, Ca",23-Feb-1883,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
13,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
15,"Budapest, Hungary",24-Dec-1886,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
17,New York City,11-Oct-18,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler
20,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan
21,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston
22,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz
23,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz
24,"Oakland, Ca",18-Dec-04,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens
25,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford
26,"Vienna, Austria",29-Apr-07,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann
27,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan
28,"Lawrence, Ks",30-Jan-20,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann
29,"Oakland, Ca",18-Dec-04,White,Na,Straight,1957,Best Director,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...
411,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
412,New York City,14-Sep-60,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo
413,"Montgomery, Al",25-May-72,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer
414,"Brooklyn, Ny",12-Nov-82,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway
415,"Mexico City, Mexico",1-Mar-83,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o
416,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder
417,"Independence, Mo",16-Jul-11,White,Christian Science,Straight,1941,Best Actress,Kitty Foyle,Ginger Rogers
418,"Concord, Ca",9-Jul-56,White,Born-Again Christian,Straight,1994,Best Actor,Philadelphia,Tom Hanks
419,New York City,3-Feb-39,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino
420,"Quincy, Il",3-May-06,White,Roman Catholic,Straight,1942,Best Supporting Actress,The Great Lie,Mary Astor
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
422,New York City,31-Oct-27,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant
423,New York City,25-Jun-1903,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere
424,"Bascom, Fl",14-Jan-41,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway
425,"Walters, Ok",13-Dec-10,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin
426,"Thomasville, Ga",27-Feb-30,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward
427,"Helena, Mt",7-May-1901,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper
428,"London, England",27-Feb-32,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
431,"Los Angeles, Ca",27-Sep-72,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow
432,"Malden, Ma",16-Jun-07,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
435,"Ilford, Essex, England",28-Dec-34,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [27]:
oscars.count() #Contamos los registros para cada columna.

birthplace            441
date_of_birth         441
race_ethnicity        441
religion              441
sexual_orientation    441
year_of_award         441
award                 441
movie                 441
person                441
dtype: int64

In [46]:
#Ahora vamos a setear el index (que era RANGEINDEX por defecto)...
#y vamos a usar la columna person y year_of_award en su lugar --> UNA PK COMPUESTA digamos.
#Asumiendo asi que una misma persona no gano el premio 2 años seguidos, debería ser una PK UNICA pero para este ejemplo no es necesario.
oscars_byID=oscars.set_index(['person','year_of_award'])
oscars_byID  #(vemos ahora que person y year_of_award desaparecen de las columnas y ahora son nuestras PKs)

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                   date_of_birth race_ethnicity  \
person               year_of_award
Lewis Milestone      1927            30-Sep-1895          White
Frank Lloyd          1930             2-Feb-1886          White
Lewis Milestone      1931            30-Sep-1895          White
Norman Taurog        1932            23-Feb-1899          White
Frank Borzage        1933            23-Apr-1894          White
Frank Lloyd          1934             2-Feb-1886          White
Frank Capra          1935            18-May-1897          White
John Ford            1936             1-Feb-1894          White
Frank Capra          1937            18-May-1897          White
Leo McCarey          1938             3-Oct-1898          White
Frank Capra          1939            18-May-1897          White
Victor Fleming       1940            23-Feb-1883          White
John Ford            1941             1-Feb-1894          White
                     1942             1-Feb-1894          White
William Wyler        1943             1-Jul-1902          White
Michael Curtiz       1944            24-Dec-1886          White
Leo McCarey          1945             3-Oct-1898          White
Jerome Robbins       1962              11-Oct-18          White
Billy Wilder         1946              22-Jun-06          White
William Wyler        1947             1-Jul-1902          White
Elia Kazan           1948               7-Sep-09          White
John Huston          1949               5-Aug-06          White
Joseph L. Mankiewicz 1950              11-Feb-09          White
                     1951              11-Feb-09          White
George Stevens       1952              18-Dec-04          White
John Ford            1953             1-Feb-1894          White
Fred Zinnemann       1954              29-Apr-07          White
Elia Kazan           1955               7-Sep-09          White
Delbert Mann         1956              30-Jan-20          White
George Stevens       1957              18-Dec-04          White
...                                          ...            ...
Mo'Nique             2010              11-Dec-67          Black
Melissa Leo          2011              14-Sep-60          White
Octavia Spencer      2012              25-May-72          Black
Anne Hathaway        2013              12-Nov-82          White
Lupita Nyong'o       2014               1-Mar-83          Black
Billy Wilder         1961              22-Jun-06          White
Ginger Rogers        1941              16-Jul-11          White
Tom Hanks            1994               9-Jul-56          White
Michael Cimino       1979               3-Feb-39          White
Mary Astor           1942               3-May-06          White
Angelina Jolie       2000               4-Jun-75          White
Lee Grant            1976              31-Oct-27          White
Anne Revere          1946            25-Jun-1903          White
Faye Dunaway         1977              14-Jan-41          White
Van Heflin           1943              13-Dec-10          White
Joanne Woodward      1958              27-Feb-30          White
Gary Cooper          1953             7-May-1901          White
Elizabeth Taylor     1967              27-Feb-32          White
Hilary Swank         2005              30-Jul-74          White
                     2005              30-Jul-74          White
Gwyneth Paltrow      1999              27-Sep-72          White
Jack Albertson       1969              16-Jun-07          White
Mo'Nique             2010              11-Dec-67          Black
Marcia Gay Harden    2001              14-Aug-59          White
Maggie Smith         1970              28-Dec-34          White
Rachel Weisz         2006               7-Mar-71          White
Danny Boyle          2009              20-Oct-56          White
Jason Robards        1977              26-Jul-22          White
James Coburn         1999              31-Aug-28          White
John Huston          1949               5-Aug-06          White

                                                religion sexual_orientation  \
person               year_of_award
Lewis Milestone      1927                             Na           Straight
Frank Lloyd          1930                             Na           Straight
Lewis Milestone      1931                             Na           Straight
Norman Taurog        1932                             Na           Straight
Frank Borzage        1933                 Roman Catholic           Straight
Frank Lloyd          1934                             Na           Straight
Frank Capra          1935                 Roman Catholic           Straight
John Ford            1936                 Roman Catholic           Bisexual
Frank Capra          1937                 Roman Catholic           Straight
Leo McCarey          1938                             Na           Straight
Frank Capra          1939                 Roman Catholic           Straight
Victor Fleming       1940                             Na           Straight
John Ford            1941                 Roman Catholic           Bisexual
                     1942                 Roman Catholic           Bisexual
William Wyler        1943                             Na           Straight
Michael Curtiz       1944                             Na           Straight
Leo McCarey          1945                             Na           Straight
Jerome Robbins       1962                         Jewish                Gay
Billy Wilder         1946                         Jewish           Straight
William Wyler        1947                             Na           Straight
Elia Kazan           1948                             Na           Straight
John Huston          1949                             Na           Straight
Joseph L. Mankiewicz 1950                         Jewish           Straight
                     1951                         Jewish           Straight
George Stevens       1952                             Na           Straight
John Ford            1953                 Roman Catholic           Bisexual
Fred Zinnemann       1954                         Jewish           Straight
Elia Kazan           1955                             Na           Straight
Delbert Mann         1956                   Presbyterian           Straight
George Stevens       1957                             Na           Straight
...                                                  ...                ...
Mo'Nique             2010                             Na           Straight
Melissa Leo          2011                             Na           Straight
Octavia Spencer      2012                             Na                 Na
Anne Hathaway        2013                      Christian           Straight
Lupita Nyong'o       2014                             Na                 Na
Billy Wilder         1961                         Jewish           Straight
Ginger Rogers        1941              Christian Science           Straight
Tom Hanks            1994           Born-Again Christian           Straight
Michael Cimino       1979                             Na           Straight
Mary Astor           1942                 Roman Catholic           Straight
Angelina Jolie       2000                       Buddhist           Bisexual
Lee Grant            1976                         Jewish           Straight
Anne Revere          1946                             Na           Straight
Faye Dunaway         1977                 Roman Catholic           Straight
Van Heflin           1943                             Na           Straight
Joanne Woodward      1958                             Na           Straight
Gary Cooper          1953                 Roman Catholic           Straight
Elizabeth Taylor     1967                         Jewish           Straight
Hilary Swank         2005                             Na           Straight
                     2005                             Na           Straight
Gwyneth Paltrow      1999                         Jewish           Straight
Jack Albertson       1969                             Na                 Na
Mo'Nique             2010                             Na           Straight
Marcia Gay Harden    2001                             Na           Straight
Maggie Smith         1970                             Na           Straight
Rachel Weisz         2006                         Jewish           Straight
Danny Boyle          2009                 Roman Catholic           Straight
Jason Robards        1977                             Na           Straight
James Coburn         1999                             Na           Straight
John Huston          1949                             Na           Straight

                                                      award  \
person               year_of_award
Lewis Milestone      1927                     Best Director
Frank Lloyd          1930                     Best Director
Lewis Milestone      1931                     Best Director
Norman Taurog        1932                     Best Director
Frank Borzage        1933                     Best Director
Frank Lloyd          1934                     Best Director
Frank Capra          1935                     Best Director
John Ford            1936                     Best Director
Frank Capra          1937                     Best Director
Leo McCarey          1938                     Best Director
Frank Capra          1939                     Best Director
Victor Fleming       1940                     Best Director
John Ford            1941                     Best Director
                     1942                     Best Director
William Wyler        1943                     Best Director
Michael Curtiz       1944                     Best Director
Leo McCarey          1945                     Best Director
Jerome Robbins       1962                     Best Director
Billy Wilder         1946                     Best Director
William Wyler        1947                     Best Director
Elia Kazan           1948                     Best Director
John Huston          1949                     Best Director
Joseph L. Mankiewicz 1950                     Best Director
                     1951                     Best Director
George Stevens       1952                     Best Director
John Ford            1953                     Best Director
Fred Zinnemann       1954                     Best Director
Elia Kazan           1955                     Best Director
Delbert Mann         1956                     Best Director
George Stevens       1957                     Best Director
...                                                     ...
Mo'Nique             2010           Best Supporting Actress
Melissa Leo          2011           Best Supporting Actress
Octavia Spencer      2012           Best Supporting Actress
Anne Hathaway        2013           Best Supporting Actress
Lupita Nyong'o       2014           Best Supporting Actress
Billy Wilder         1961                     Best Director
Ginger Rogers        1941                      Best Actress
Tom Hanks            1994                        Best Actor
Michael Cimino       1979                     Best Director
Mary Astor           1942           Best Supporting Actress
Angelina Jolie       2000           Best Supporting Actress
Lee Grant            1976           Best Supporting Actress
Anne Revere          1946           Best Supporting Actress
Faye Dunaway         1977                      Best Actress
Van Heflin           1943             Best Supporting Actor
Joanne Woodward      1958                      Best Actress
Gary Cooper          1953                        Best Actor
Elizabeth Taylor     1967                      Best Actress
Hilary Swank         2005                      Best Actress
                     2005                      Best Actress
Gwyneth Paltrow      1999                      Best Actress
Jack Albertson       1969             Best Supporting Actor
Mo'Nique             2010           Best Supporting Actress
Marcia Gay Harden    2001           Best Supporting Actress
Maggie Smith         1970                      Best Actress
Rachel Weisz         2006           Best Supporting Actress
Danny Boyle          2009                     Best Director
Jason Robards        1977             Best Supporting Actor
James Coburn         1999             Best Supporting Actor
John Huston          1949                     Best Director

                                                               movie
person               year_of_award
Lewis Milestone      1927                        Two Arabian Knights
Frank Lloyd          1930                            The Divine Lady
Lewis Milestone      1931             All Quiet on the Western Front
Norman Taurog        1932                                     Skippy
Frank Borzage        1933                                   Bad Girl
Frank Lloyd          1934                                  Cavalcade
Frank Capra          1935                      It Happened One Night
John Ford            1936                               The Informer
Frank Capra          1937                     Mr. Deeds Goes to Town
Leo McCarey          1938                            The Awful Truth
Frank Capra          1939                 You Can't Take It with You
Victor Fleming       1940                         Gone with the Wind
John Ford            1941                        The Grapes of Wrath
                     1942                    How Green Was My Valley
William Wyler        1943                               Mrs. Miniver
Michael Curtiz       1944                                 Casablanca
Leo McCarey          1945                               Going My Way
Jerome Robbins       1962                            West Side Story
Billy Wilder         1946                           The Lost Weekend
William Wyler        1947                The Best Years of Our Lives
Elia Kazan           1948                      Gentleman's Agreement
John Huston          1949           The Treasure of the Sierra Madre
Joseph L. Mankiewicz 1950                    A Letter to Three Wives
                     1951                              All About Eve
George Stevens       1952                         A Place in the Sun
John Ford            1953                              The Quiet Man
Fred Zinnemann       1954                      From Here to Eternity
Elia Kazan           1955                          On the Waterfront
Delbert Mann         1956                                      Marty
George Stevens       1957                                      Giant
...                                                              ...
Mo'Nique             2010                                   Precious
Melissa Leo          2011                                The Fighter
Octavia Spencer      2012                                   The Help
Anne Hathaway        2013                            Les MisÌ©rables
Lupita Nyong'o       2014                           12 Years a Slave
Billy Wilder         1961                              The Apartment
Ginger Rogers        1941                                Kitty Foyle
Tom Hanks            1994                               Philadelphia
Michael Cimino       1979                            The Deer Hunter
Mary Astor           1942                              The Great Lie

In [34]:
oscars_byID.count() #Contamos los registros para cada columna.

birthplace            441
date_of_birth         441
race_ethnicity        441
religion              441
sexual_orientation    441
award                 441
movie                 441
dtype: int64

In [58]:
#Ahora hacemos lo mismo pero desde la lectura inicial para generar el indice (con index_col). 
#Y usamos \ para bajar lineas (ya que ahora si nuestro codigo en una linea es muy extenso)
oscars_byID2= pd.read_csv('data/Oscars-demographics-DFE.csv', encoding='latin-1', \
                          index_col=['person','year_of_award'])
oscars_byID2

                                     _unit_id  _golden _unit_state  \
person               year_of_award
Lewis Milestone      1927           670454353    False   finalized
Frank Lloyd          1930           670454354    False   finalized
Lewis Milestone      1931           670454355    False   finalized
Norman Taurog        1932           670454356    False   finalized
Frank Borzage        1933           670454357    False   finalized
Frank Lloyd          1934           670454358    False   finalized
Frank Capra          1935           670454359    False   finalized
John Ford            1936           670454360    False   finalized
Frank Capra          1937           670454361    False   finalized
Leo McCarey          1938           670454362    False   finalized
Frank Capra          1939           670454363    False   finalized
Victor Fleming       1940           670454364    False   finalized
John Ford            1941           670454365    False   finalized
                     1942           670454366    False   finalized
William Wyler        1943           670454367    False   finalized
Michael Curtiz       1944           670454368    False   finalized
Leo McCarey          1945           670454369    False   finalized
Jerome Robbins       1962           670454370    False   finalized
Billy Wilder         1946           670454371    False   finalized
William Wyler        1947           670454372    False   finalized
Elia Kazan           1948           670454373    False   finalized
John Huston          1949           670454374     True      golden
Joseph L. Mankiewicz 1950           670454375    False   finalized
                     1951           670454376    False   finalized
George Stevens       1952           670454377    False   finalized
John Ford            1953           670454378    False   finalized
Fred Zinnemann       1954           670454379    False   finalized
Elia Kazan           1955           670454380    False   finalized
Delbert Mann         1956           670454381    False   finalized
George Stevens       1957           670454382    False   finalized
...                                       ...      ...         ...
Mo'Nique             2010           670454764     True      golden
Melissa Leo          2011           670454765    False   finalized
Octavia Spencer      2012           670454766    False   finalized
Anne Hathaway        2013           670454767    False   finalized
Lupita Nyong'o       2014           670454768    False   finalized
Billy Wilder         1961           670927629    False   finalized
Ginger Rogers        1941           670939613    False   finalized
Tom Hanks            1994           670944094    False   finalized
Michael Cimino       1979           670944168    False   finalized
Mary Astor           1942           670944316    False   finalized
Angelina Jolie       2000           670944478    False   finalized
Lee Grant            1976           670944543    False   finalized
Anne Revere          1946           670944623    False   finalized
Faye Dunaway         1977           670944674    False   finalized
Van Heflin           1943           670944755    False   finalized
Joanne Woodward      1958           670944822    False   finalized
Gary Cooper          1953           670944835    False   finalized
Elizabeth Taylor     1967           670944920    False   finalized
Hilary Swank         2005           670944948    False   finalized
                     2005           670945043     True      golden
Gwyneth Paltrow      1999           670945693    False   finalized
Jack Albertson       1969           670945790    False   finalized
Mo'Nique             2010           670945834    False   finalized
Marcia Gay Harden    2001           670945895    False   finalized
Maggie Smith         1970           670946199    False   finalized
Rachel Weisz         2006           670946276    False   finalized
Danny Boyle          2009           670946299    False   finalized
Jason Robards        1977           670964912    False   finalized
James Coburn         1999           670964956    False   finalized
John Huston          1949           670972898    False   finalized

                                    _trusted_judgments _last_judgment_at  \
person               year_of_award
Lewis Milestone      1927                            3      2/10/15 3:45
Frank Lloyd          1930                            3      2/10/15 2:03
Lewis Milestone      1931                            3      2/10/15 2:05
Norman Taurog        1932                            3      2/10/15 2:04
Frank Borzage        1933                            3      2/10/15 1:48
Frank Lloyd          1934                            3      2/10/15 3:50
Frank Capra          1935                            3      2/10/15 2:07
John Ford            1936                            3      2/10/15 1:46
Frank Capra          1937                            3      2/10/15 1:47
Leo McCarey          1938                            3      2/10/15 2:05
Frank Capra          1939                            3      2/10/15 2:04
Victor Fleming       1940                            3      2/10/15 2:10
John Ford            1941                            3      2/10/15 2:12
                     1942                            3      2/10/15 2:02
William Wyler        1943                            3      2/10/15 3:57
Michael Curtiz       1944                            3      2/10/15 2:02
Leo McCarey          1945                            3      2/10/15 2:29
Jerome Robbins       1962                            3      2/10/15 1:55
Billy Wilder         1946                            3      2/10/15 4:02
William Wyler        1947                            3      2/10/15 2:12
Elia Kazan           1948                            3      2/10/15 1:46
John Huston          1949                           82               NaN
Joseph L. Mankiewicz 1950                            3      2/10/15 3:50
                     1951                            3      2/10/15 1:51
George Stevens       1952                            3      2/10/15 2:15
John Ford            1953                            3      2/10/15 2:15
Fred Zinnemann       1954                            3      2/10/15 1:57
Elia Kazan           1955                            3      2/10/15 3:50
Delbert Mann         1956                            3      2/10/15 3:53
George Stevens       1957                            3      2/10/15 3:50
...                                                ...               ...
Mo'Nique             2010                           86               NaN
Melissa Leo          2011                            3      2/10/15 1:56
Octavia Spencer      2012                            3      2/10/15 2:18
Anne Hathaway        2013                            3      2/10/15 2:18
Lupita Nyong'o       2014                            3      2/10/15 2:10
Billy Wilder         1961                            3      2/10/15 2:02
Ginger Rogers        1941                            3      2/10/15 1:53
Tom Hanks            1994                            3      2/10/15 2:18
Michael Cimino       1979                            3      2/10/15 3:55
Mary Astor           1942                            3      2/10/15 2:05
Angelina Jolie       2000                            3      2/10/15 1:49
Lee Grant            1976                            3      2/10/15 2:12
Anne Revere          1946                            3      2/10/15 2:11
Faye Dunaway         1977                            3      2/10/15 2:05
Van Heflin           1943                            3      2/10/15 2:04
Joanne Woodward      1958                            3      2/10/15 4:14
Gary Cooper          1953                            3      2/10/15 2:08
Elizabeth Taylor     1967                            3      2/10/15 3:58
Hilary Swank         2005                            3      2/10/15 2:06
                     2005                           86               NaN
Gwyneth Paltrow      1999                            3      2/10/15 1:49
Jack Albertson       1969                            3      2/10/15 2:08
Mo'Nique             2010                            3      2/10/15 2:07
Marcia Gay Harden    2001                            3      2/10/15 2:13
Maggie Smith         1970                            3      2/10/15 2:03
Rachel Weisz         2006                            3      2/10/15 2:00
Danny Boyle          2009                            3      2/10/15 2:04
Jason Robards        1977                            3      2/10/15 2:03
James Coburn         1999                            3      2/10/15 2:01
John Huston          1949                            3      2/10/15 2:01

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                    birthplace:confidence date_of_birth  \
person               year_of_award
Lewis Milestone      1927                          1.0000   30-Sep-1895
Frank Lloyd          1930                          1.0000    2-Feb-1886
Lewis Milestone      1931                          1.0000   30-Sep-1895
Norman Taurog        1932                          1.0000   23-Feb-1899
Frank Borzage        1933                          1.0000   23-Apr-1894
Frank Lloyd          1934                          1.0000    2-Feb-1886
Frank Capra          1935                          1.0000   18-May-1897
John Ford            1936                          1.0000    1-Feb-1894
Frank Capra          1937                          1.0000   18-May-1897
Leo McCarey          1938                          1.0000    3-Oct-1898
Frank Capra          1939                          1.0000   18-May-1897
Victor Fleming       1940                          1.0000   23-Feb-1883
John Ford            1941                          1.0000    1-Feb-1894
                     1942                          1.0000    1-Feb-1894
William Wyler        1943                          1.0000    1-Jul-1902
Michael Curtiz       1944                          1.0000   24-Dec-1886
Leo McCarey          1945                          1.0000    3-Oct-1898
Jerome Robbins       1962                          1.0000     11-Oct-18
Billy Wilder         1946                          0.6667     22-Jun-06
William Wyler        1947                          1.0000    1-Jul-1902
Elia Kazan           1948                          1.0000      7-Sep-09
John Huston          1949                          1.0000      5-Aug-06
Joseph L. Mankiewicz 1950                          1.0000     11-Feb-09
                     1951                          1.0000     11-Feb-09
George Stevens       1952                          1.0000     18-Dec-04
John Ford            1953                          1.0000    1-Feb-1894
Fred Zinnemann       1954                          1.0000     29-Apr-07
Elia Kazan           1955                          1.0000      7-Sep-09
Delbert Mann         1956                          1.0000     30-Jan-20
George Stevens       1957                          1.0000     18-Dec-04
...                                                   ...           ...
Mo'Nique             2010                          1.0000     11-Dec-67
Melissa Leo          2011                          1.0000     14-Sep-60
Octavia Spencer      2012                          1.0000     25-May-72
Anne Hathaway        2013                          1.0000     12-Nov-82
Lupita Nyong'o       2014                          1.0000      1-Mar-83
Billy Wilder         1961                          1.0000     22-Jun-06
Ginger Rogers        1941                          1.0000     16-Jul-11
Tom Hanks            1994                          1.0000      9-Jul-56
Michael Cimino       1979                          1.0000      3-Feb-39
Mary Astor           1942                          1.0000      3-May-06
Angelina Jolie       2000                          1.0000      4-Jun-75
Lee Grant            1976                          1.0000     31-Oct-27
Anne Revere          1946                          1.0000   25-Jun-1903
Faye Dunaway         1977                          1.0000     14-Jan-41
Van Heflin           1943                          1.0000     13-Dec-10
Joanne Woodward      1958                          1.0000     27-Feb-30
Gary Cooper          1953                          1.0000    7-May-1901
Elizabeth Taylor     1967                          1.0000     27-Feb-32
Hilary Swank         2005                          1.0000     30-Jul-74
                     2005                          1.0000     30-Jul-74
Gwyneth Paltrow      1999                          1.0000     27-Sep-72
Jack Albertson       1969                          1.0000     16-Jun-07
Mo'Nique             2010                          1.0000     11-Dec-67
Marcia Gay Harden    2001                          1.0000     14-Aug-59
Maggie Smith         1970                          1.0000     28-Dec-34
Rachel Weisz         2006                          1.0000      7-Mar-71
Danny Boyle          2009                          1.0000     20-Oct-56
Jason Robards        1977                          1.0000     26-Jul-22
James Coburn         1999                          1.0000     31-Aug-28
John Huston          1949                          1.0000      5-Aug-06

                                    date_of_birth:confidence race_ethnicity  \
person               year_of_award
Lewis Milestone      1927                             1.0000          White
Frank Lloyd          1930                             1.0000          White
Lewis Milestone      1931                             1.0000          White
Norman Taurog        1932                             1.0000          White
Frank Borzage        1933                             1.0000          White
Frank Lloyd          1934                             1.0000          White
Frank Capra          1935                             1.0000          White
John Ford            1936                             1.0000          White
Frank Capra          1937                             1.0000          White
Leo McCarey          1938                             1.0000          White
Frank Capra          1939                             1.0000          White
Victor Fleming       1940                             1.0000          White
John Ford            1941                             1.0000          White
                     1942                             1.0000          White
William Wyler        1943                             1.0000          White
Michael Curtiz       1944                             1.0000          White
Leo McCarey          1945                             1.0000          White
Jerome Robbins       1962                             1.0000          White
Billy Wilder         1946                             1.0000          White
William Wyler        1947                             1.0000          White
Elia Kazan           1948                             1.0000          White
John Huston          1949                             1.0000          White
Joseph L. Mankiewicz 1950                             1.0000          White
                     1951                             1.0000          White
George Stevens       1952                             1.0000          White
John Ford            1953                             1.0000          White
Fred Zinnemann       1954                             1.0000          White

In [66]:
#VER COMO HACER ESTO. Me tira error:
#Y ademas con names le especificamos las columnas que queremos (Asi nos queda igual al caso anterior)
#Osea aplicamos lo de los indices y tambien el filtrado de columnas en el read_csv() (las 2 cosas juntas):

#Vector de nombres con las columnas que queremos usar: 
Vnames=['birthplace','date_of_birth','race_ethnicity','religion','sexual_orientation','award','movie','person','year_of_award']

oscars_byID2_y_Columnas_Filtradas= pd.read_csv('data/Oscars-demographics-DFE.csv', encoding='latin-1', \
                                  names=Vnames) #,  \
                                  #index_col=['person','year_of_award'])
oscars_byID2_y_Columnas_Filtradas

,,,,,,,,,,,,,,,,,,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,award,movie,person,year_of_award
_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,race_ethnicity:confidence,religion,religion:confidence,sexual_orientation,sexual_orientation:confidence,year_of_award,year_of_award:confidence,award,biourl,birthplace_gold,date_of_birth_gold,movie,person,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
670454353,FALSE,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1,30-Sep-1895,1,White,1,Na,1,Straight,1,1927,1,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,Two Arabian Knights,Lewis Milestone,NaN,NaN,NaN,NaN
670454354,FALSE,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1,2-Feb-1886,1,White,1,Na,1,Straight,0.6842,1930,1,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,The Divine Lady,Frank Lloyd,NaN,NaN,NaN,NaN
670454355,FALSE,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1,30-Sep-1895,1,White,1,Na,1,Straight,1,1931,0.6667,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,All Quiet on the Western Front,Lewis Milestone,NaN,NaN,NaN,NaN
670454356,FALSE,finalized,3,2/10/15 2:04,"Chicago, Il",1,23-Feb-1899,1,White,1,Na,1,Straight,1,1932,1,Best Director,http://www.nndb.com/people/544/000041421/,NaN,NaN,Skippy,Norman Taurog,NaN,NaN,NaN,NaN
670454357,FALSE,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1,23-Apr-1894,1,White,1,Roman Catholic,1,Straight,1,1933,1,Best Director,http://www.nndb.com/people/292/000044160/,NaN,NaN,Bad Girl,Frank Borzage,NaN,NaN,NaN,NaN
670454358,FALSE,finalized,3,2/10/15 3:50,"Glasgow, Scotland",1,2-Feb-1886,1,White,1,Na,1,Straight,1,1934,1,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,Cavalcade,Frank Lloyd,NaN,NaN,NaN,NaN
670454359,FALSE,finalized,3,2/10/15 2:07,"Bisacquino, Sicily, Italy",1,18-May-1897,1,White,1,Roman Catholic,1,Straight,1,1935,1,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,It Happened One Night,Frank Capra,NaN,NaN,NaN,NaN
670454360,FALSE,finalized,3,2/10/15 1:46,"Cape Elizabeth, Me",1,1-Feb-1894,1,White,1,Roman Catholic,1,Bisexual,1,1936,1,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Informer,John Ford,NaN,NaN,NaN,NaN
670454361,FALSE,finalized,3,2/10/15 1:47,"Bisacquino, Sicily, Italy",1,18-May-1897,1,White,1,Roman Catholic,1,Straight,1,1937,1,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,Mr. Deeds Goes to Town,Frank Capra,NaN,NaN,NaN,NaN
670454362,FALSE,finalized,3,2/10/15 2:05,"Los Angeles, Ca",1,3-Oct-1898,1,White,1,Na,1,Straight,1,1938,1,Best Director,http://www.nndb.com/people/380/000044248/,NaN,NaN,The Awful Truth,Leo McCarey,NaN,NaN,NaN,NaN
670454363,FALSE,finalized,3,2/10/15 2:04,"Bisacquino, Sicily, Italy",1,18-May-1897,1,White,1,Roman Catholic,1,Straight,1,1939,1,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,You Can't Take It with You,Frank Capra,NaN,NaN,NaN,NaN
670454364,FALSE,finalized,3,2/10/15 2:10,"Pasadena, Ca",1,23-Feb-1883,1,White,1,Na,1,Straight,1,1940,1,Best Director,http://www.nndb.com/people/416/000041293/,NaN,NaN,Gone with the Wind,Victor Fleming,NaN,NaN,NaN,NaN
670454365,FALSE,finalized,3,2/10/15 2:12,"Cape Elizabeth, Me",1,1-Feb-1894,1,White,1,Roman Catholic,1,Bisexual,1,1941,1,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Grapes of Wrath,John Ford,NaN,NaN,NaN,NaN
670454366,FALSE,finalized,3,2/10/15 2:02,"Cape Elizabeth, Me",1,1-Feb-1894,1,White,1,Roman Catholic,1,Bisexual,1,1942,1,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,How Green Was My Valley,John Ford,NaN,NaN,NaN,NaN
670454367,FALSE,finalized,3,2/10/15 3:57,"Mulhouse, Haut-Rhin, Alsace, France",1,1-Jul-1902,1,White,1,Na,1,Straight,1,1943,1,Best Director,http://www.nndb.com/people/463/000032367/,NaN,NaN,Mrs. Miniver,William Wyler,NaN,NaN,NaN,NaN
670454368,FALSE,finalized,3,2/10/15 2:02,"Budapest, Hungary",1,24-Dec-1886,1,White,1,Na,1,Straight,1,1944,1,Best Director,http://www.nndb.com/people/676/000032580/,NaN,NaN,Casablanca,Michael Curtiz,NaN,NaN,NaN,NaN
670454369,FALSE,finalized,3,2/10/15 2:29,"Los Angeles, Ca",1,3-Oct-1898,1,White,1,Na,1,Straight,1,1945,1,Best Director,http://www.nndb.com/people/380/000044248/,NaN,NaN,Going My Way,Leo McCarey,NaN,NaN,NaN,NaN
670454370,FALSE,finalized,3,2/10/15 1:55,New York City,1,11-Oct-18,1,White,1,Jewish,1,Gay,1,1962,1,Best Director,http://www.nndb.com/people/281/000064089/,NaN,NaN,West Side Story,Jerome Robbins,NaN,NaN,NaN,NaN
670454371,FALSE,finalized,3,2/10/15 4:02,"Sucha, Galicia, Austria",0.6667,22-Jun-06,1,White,1,Jewish,1,Straight,1,1946,1,Best Director,http://www.nndb.com/people/982/000024910/,NaN,NaN,The Lost Weekend,Billy Wilder,NaN,NaN,NaN,NaN
670454372,FALSE,finalized,3,2/10/15 2:12,"Mulhouse, Haut-Rhin, Alsace, France",1,1-Jul-1902,1,White,1,Na,1,Straight,1,1947,1,Best Director,http://www.nndb.com/people/463/000032367/,NaN,NaN,The Best Years of Our Lives,William Wyler,NaN,NaN,NaN,NaN
670454373,FALSE,finalized,3,2/10/15 1:46,"Istanbul, Turkey",1,7-Sep-09,1,White,1,Na,1,Straight,1,1948,1,Best Director,http://www.nndb.com/people/537/000026459/,NaN,NaN,Gentleman's Agreement,Elia Kazan,NaN,NaN,NaN,NaN
670454374,TRUE,golden,82,NaN,"Nevada, Mo",1,5-Aug-06,1,White,1,Na,1,Straight,1,1949,1,Best Director,http://www.nndb.com/people/704/000024632/,NaN,5-Aug-06,The Treasure of the Sierra Madre,John Huston,NaN,NaN,NaN,NaN
670454375,FALSE,finalized,3,2/10/15 3:50,"Wilkes-Barre, Pa",1,11-Feb-09,1,White,1,Jewish,1,Straight,1,1950,1,Best Director,http://www.nndb.com/people/723/000032627/,NaN,NaN,A Letter to Three Wives,Joseph L. Mankiewicz,NaN,NaN,NaN,NaN
670454376,FALSE,finalized,3,2/10/15 1:51,"Wilkes-Barre, Pa",1,11-Feb-09,1,White,1,Jewish,1,Straight,1,1951,1,Best Director,http://www.nndb.com/people/723/000032627/,NaN,NaN,All About Eve,Joseph L. Mankiewicz,NaN,NaN,NaN,NaN
670454377,FALSE,finalized,3,2/10/15 2:15,"Oakland, Ca",1,18-Dec-04,1,White,1,Na,1,Straight,1,1952,1,Best Director,http://www.nndb.com/people/382/000044250/,NaN,NaN,A Place in the Sun,George Stevens,NaN,NaN,NaN,NaN
670454378,FALSE,finalized,3,2/10/15 2:15,"Cape Elizabeth, Me",1,1-Feb-1894,1,White,1,Roman Catholic,1,Bisexual,1,1953,1,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Quiet Man,John Ford,NaN,NaN,NaN,NaN
670454379,FALSE,finalized,3,2/10/15 1:57,"Vienna, Austria",1,29-Apr-07,1,White,1,Jewish,1,Straight,1,1954,1,Best Director,http://www.nndb.com/people/538/000032442/,NaN,NaN,From Here to Eternity,Fred Zinnemann,NaN,NaN,NaN,NaN
670454380,FALSE,finalized,3,2/10/15 3:50,"Istanbul, Turkey",1,7-Sep-09,1,White,1,Na,1,Straight,1,1955,1,Best Director,http://www.nndb.com/people/537/000026459/,NaN,NaN,On the Waterfront,Elia Kazan,NaN,NaN,NaN,NaN
670454381,FALSE,finalized,3,2/10/15 3:53,"Lawrence, Ks",1,30-Jan-20,1,White,1,Presbyterian,1,Straight,1,1956,1,Best Director,http://www.nndb.com/people/384/000044252/,NaN,NaN,Marty,Delbert Mann,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670454764,TRUE,golden,86,NaN,"Woodlawn, Md",1,11-Dec-67,0.9631,Black,1,Na,1,Straight,1,2010,1,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,NaN,11-Dec-67,Precious,Mo'Nique,Black,NaN,NaN,NaN
670454765,FALSE,finalized,3,2/10/15 1:56,New York City,1,14-Sep-60,1,White,1,Na,1,Straight,1,2011,1,Best Supporting Actress,http://www.nndb.com/people/327/000042201/,NaN,NaN,The Fighter,Melissa Leo,NaN,NaN,NaN,NaN
670454766,FALSE,finalized,3,2/10/15 2:18,"Montgomery, Al",1,25-May-72,1,Black,1,Na,1,Na,1,2012,1,Best Supporting Actress,http://www.nndb.com/people/304/000281458/,NaN,NaN,The Help,Octavia Spencer,NaN,NaN,NaN,NaN
670454767,FALSE,finalized,3,2/10/15 2:18,"Brooklyn, Ny",1,12-Nov-82,1,White,1,Christian,1,Straight,1,2013,1,Best Supporting Actress,http://www.nndb.com/people/220/000032124/,NaN,NaN,Les MisÌ©rables,Anne Hathaway,NaN,NaN,NaN,NaN
670454768,FALSE,finalized,3,2/10/15 2:10,"Mexico City, Mexico",1,1-Mar-83,1,Black,1,Na,1,Na,1,2014,1,Best Supporting Actress,http://www.nndb.com/people/570/000380427/,NaN,NaN,12 Years a Slave,Lupita Nyong'o,NaN,NaN,NaN,NaN
670927629,FALSE,finalized,3,2/10/15 2:02,"Sucha, Galicia, Austria",1,22-Jun-06,1,White,1,Jewish,1,Straight,1,1961,1,Best Director,http://www.nndb.com/people/982/000024910/,NaN,NaN,The Apartment,Billy Wilder,NaN,NaN,NaN,NaN
670939613,FALSE,finalized,3,2/10/15 1:53,"Independence, Mo",1,16-Jul-11,1,White,1,Christian Science,1,Straight,1,1941,1,Best Actress,http://www.nndb.com/people/635/000043506/,NaN,NaN,Kitty Foyle,Ginger Rogers,NaN,NaN,NaN,NaN
670944094,FALSE,finalized,3,2/10/15 2:18,"Concord, Ca",1,9-Jul-56,1,White,1,Born-Again Christian,1,Straight,1,1994,1,Best Actor,http://www.nndb.com/people/687/000022621/,NaN,NaN,Philadelphia,Tom Hanks,NaN,NaN,NaN,NaN
670944168,FALSE,finalized,3,2/10/15 3:55,New York City,1,3-Feb-39,1,White,1,Na,1,Straight,1,1979,0.6667,Best Director,http://www.nndb.com/people/810/000043681/,NaN,NaN,The Deer Hunter,Michael Cimino,NaN,NaN,NaN,NaN
670944316,FALSE,finalized,3,2/10/15 2:05,"Quincy, Il",1,3-May-06,1,White,1,Roman Catholic,1,Straight,1,1942,1,Best Supporting Actress,http://www.nndb.com/people/690/000042564/,NaN,NaN,The Great Lie,Mary Astor,NaN,NaN,NaN,NaN
670944478,FALSE,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1,4-Jun-75,1,White,1,Buddhist,1,Bisexual,1,2000,1,Best Supporting Actress,http://www.nndb.com/people/493/000023424/,NaN,NaN,"Girl, Interrupted",Angelina Jolie,NaN,NaN,NaN,NaN
670944543,FALSE,finalized,3,2/10/15 2:12,New York City,1,31-Oct-27,1,White,1,Jewish,1,Straight,1,1976,1,Best Supporting Actress,http://www.nndb.com/people/409/000032313/,NaN,NaN,Shampoo,Lee Grant,NaN,NaN,NaN,NaN
670944623,FALSE,finalized,3,2/10/15 2:11,New York City,1,25-Jun-1903,1,White,1,Na,1,Straight,1,1946,1,Best Supporting Actress,http://www.nndb.com/people/081/000063889/,NaN,NaN,National Velvet,Anne Revere,NaN,NaN,NaN,NaN
670944674,FALSE,finalized,3,2/10/15 2:05,"Bascom, Fl",1,14-Jan-41,1,White,1,Roman Catholic,1,Straight,1,1977,1,Best Actress,http://www.nndb.com/people/884/000022818/,NaN,NaN,Network,Faye Dunaway,NaN,NaN,NaN,NaN
670944755,FALSE,finalized,3,2/10/15 2:04,"Walters, Ok",1,13-Dec-10,1,White,1,Na,1,Straight,1,1943,1,Best Supporting Actor,http://www.nndb.com/people/680/000042554/,NaN,NaN,Johnny Eager,Van Heflin,NaN,NaN,NaN,NaN
670944822,FALSE,finalized,3,2/10/15 4:14,"Thomasville, Ga",1,27-Feb-30,1,White,1,Na,1,Straight,1,1958,1,Best Actress,http://www.nndb.com/people/747/000043618/,NaN,NaN,The Three Faces of Eve,Joanne Woodward,NaN,NaN,NaN,NaN
670944835,FALSE,finalized,3,2/10/15 2:08,"Helena, Mt",1,7-May-1901,1,White,1,Roman Catholic,1,Straight,1,1953,1,Best Actor,http://www.nndb.com/people/740/000031647/,NaN,NaN,High Noon,Gary Cooper,NaN,NaN,NaN,NaN
670944920,FALSE,finalized,3,2/10/15 3:58,"London, England",1,27-Feb-32,1,White,1,Jewish,1,Straight,1,1967,1,Best Actress,http://www.nndb.com/people/624/000023555/,NaN,NaN,Who's Afraid of Virginia Woolf?,Elizabeth Taylor,NaN,NaN,NaN,NaN
670944948,FALSE,finalized,3,2/10/15 2:06,"Lincoln, Ne",1,30-Jul-74,1,White,1,Na,1,Straight,1,2005,1,Best Actress,http://www.nndb.com/people/333/000026255/,NaN,NaN,Million Dollar Baby,Hilary Swank,NaN,NaN,NaN,NaN
670945043,TRUE,golden,86,NaN,"Lincoln, Ne",1,30-Jul-74,1,White,1,Na,1,Straight,1,2005,1,Best Actress,http://www.nndb.com/people/333/000026255/,NaN,NaN,Million Dollar Baby,Hilary Swank,NaN,NaN,NaN,NaN
670945693,FALSE,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1,27-Sep-72,1,White,1,Jewish,1,Straight,1,1999,1,Best Actress,http://www.nndb.com/people/592/000023523/,NaN,NaN,Shakespeare in Love,Gwyneth Paltrow,NaN,NaN,NaN,NaN
670945790,FALSE,finalized,3,2/10/15 2:08,"Malden, Ma",1,16-Jun-07,1,White,1,Na,1,Na,1,1969,1,Best Supporting Actor,http://www.nndb.com/people/559/000049412/,NaN,NaN,The Subject Was Roses,Jack Albertson,NaN,NaN,NaN,NaN
670945834,FALSE,finalized,3,2/10/15 2:07,"Woodlawn, Md",1,11-Dec-67,1,Black,1,Na,1,Straight,1,2010,1,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,NaN,NaN,Precious,Mo'Nique,NaN,NaN,NaN,NaN
670945895,FALSE,finalized,3,2/10/15 2:13,"La Jolla, Ca",1,14-Aug-59,1,White,1,Na,1,Straight,1,2001,1,Best Supporting Actress,http://www.nndb.com/people/641/000025566/,NaN,NaN,Pollock,Marcia Gay Harden,NaN,NaN,NaN,NaN
670946199,FALSE,finalized,3,2/10/15 2:03,"Ilford, Essex, England",1,28-Dec-34,1,White,1,Na,1,Straight,1,1970,1,Best Actress,http://www.nndb.com/people/260/000030170/,NaN,NaN,The Prime of Miss Jean Brodie,Maggie Smith,NaN,NaN,NaN,NaN
670946276,FALSE,finalized,3,2/10/15 2:00,"London, England",1,7-Mar-71,1,White,1,Jewish,1,Straight,1,2006,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,Rachel Weisz,NaN,NaN,NaN,NaN
670946299,FALSE,finalized,3,2/10/15 2:04,"Manchester, England",1,20-Oct-56,1,White,1,Roman Catholic,1,Straight,1,2009,1,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,Danny Boyle,NaN,NaN,NaN,NaN
670964912,FALSE,finalized,3,2/10/15 2:03,"Chicago, Il",1,26-Jul-22,1,White,1,Na,1,Straight,1,1977,1,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,Jason Robards,NaN,NaN,NaN,NaN
670964956,FALSE,finalized,3,2/10/15 2:01,"Laurel, Ne",1,31-Aug-28,1,White,1,Na,1,Straight,1,1999,1,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,James Coburn,NaN,NaN,NaN,NaN
670972898,FALSE,finalized,3,2/10/15 2:01,"Nevada, Mo",1,5-Aug-06,1,White,1,Na,1,Straight,1,1949,1,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,John Huston,NaN,NaN,NaN,NaN

In [67]:
#Como creamos esto de los indices tambien lo podemos eliminar y que quede como antes con RANGEINDEX:
oscars_byID2.reset_index() 
#Nos vuelve a generar las columnas y los datos que teniamos como indices los pasa a columnas como teniamos antes de crear los indices.

,person,year_of_award,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,...,year_of_award:confidence,award,biourl,birthplace_gold,date_of_birth_gold,movie,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
0,Lewis Milestone,1927,670454353,False,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1.0000,30-Sep-1895,...,1.0000,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,Two Arabian Knights,NaN,NaN,NaN,NaN
1,Frank Lloyd,1930,670454354,False,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1.0000,2-Feb-1886,...,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,The Divine Lady,NaN,NaN,NaN,NaN
2,Lewis Milestone,1931,670454355,False,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1.0000,30-Sep-1895,...,0.6667,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,All Quiet on the Western Front,NaN,NaN,NaN,NaN
3,Norman Taurog,1932,670454356,False,finalized,3,2/10/15 2:04,"Chicago, Il",1.0000,23-Feb-1899,...,1.0000,Best Director,http://www.nndb.com/people/544/000041421/,NaN,NaN,Skippy,NaN,NaN,NaN,NaN
4,Frank Borzage,1933,670454357,False,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1.0000,23-Apr-1894,...,1.0000,Best Director,http://www.nndb.com/people/292/000044160/,NaN,NaN,Bad Girl,NaN,NaN,NaN,NaN
5,Frank Lloyd,1934,670454358,False,finalized,3,2/10/15 3:50,"Glasgow, Scotland",1.0000,2-Feb-1886,...,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,Cavalcade,NaN,NaN,NaN,NaN
6,Frank Capra,1935,670454359,False,finalized,3,2/10/15 2:07,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,...,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,It Happened One Night,NaN,NaN,NaN,NaN
7,John Ford,1936,670454360,False,finalized,3,2/10/15 1:46,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Informer,NaN,NaN,NaN,NaN
8,Frank Capra,1937,670454361,False,finalized,3,2/10/15 1:47,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,...,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,Mr. Deeds Goes to Town,NaN,NaN,NaN,NaN
9,Leo McCarey,1938,670454362,False,finalized,3,2/10/15 2:05,"Los Angeles, Ca",1.0000,3-Oct-1898,...,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,NaN,NaN,The Awful Truth,NaN,NaN,NaN,NaN
10,Frank Capra,1939,670454363,False,finalized,3,2/10/15 2:04,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,...,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,You Can't Take It with You,NaN,NaN,NaN,NaN
11,Victor Fleming,1940,670454364,False,finalized,3,2/10/15 2:10,"Pasadena, Ca",1.0000,23-Feb-1883,...,1.0000,Best Director,http://www.nndb.com/people/416/000041293/,NaN,NaN,Gone with the Wind,NaN,NaN,NaN,NaN
12,John Ford,1941,670454365,False,finalized,3,2/10/15 2:12,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Grapes of Wrath,NaN,NaN,NaN,NaN
13,John Ford,1942,670454366,False,finalized,3,2/10/15 2:02,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,How Green Was My Valley,NaN,NaN,NaN,NaN
14,William Wyler,1943,670454367,False,finalized,3,2/10/15 3:57,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,...,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,NaN,NaN,Mrs. Miniver,NaN,NaN,NaN,NaN
15,Michael Curtiz,1944,670454368,False,finalized,3,2/10/15 2:02,"Budapest, Hungary",1.0000,24-Dec-1886,...,1.0000,Best Director,http://www.nndb.com/people/676/000032580/,NaN,NaN,Casablanca,NaN,NaN,NaN,NaN
16,Leo McCarey,1945,670454369,False,finalized,3,2/10/15 2:29,"Los Angeles, Ca",1.0000,3-Oct-1898,...,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,NaN,NaN,Going My Way,NaN,NaN,NaN,NaN
17,Jerome Robbins,1962,670454370,False,finalized,3,2/10/15 1:55,New York City,1.0000,11-Oct-18,...,1.0000,Best Director,http://www.nndb.com/people/281/000064089/,NaN,NaN,West Side Story,NaN,NaN,NaN,NaN
18,Billy Wilder,1946,670454371,False,finalized,3,2/10/15 4:02,"Sucha, Galicia, Austria",0.6667,22-Jun-06,...,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,NaN,NaN,The Lost Weekend,NaN,NaN,NaN,NaN
19,William Wyler,1947,670454372,False,finalized,3,2/10/15 2:12,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,...,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,NaN,NaN,The Best Years of Our Lives,NaN,NaN,NaN,NaN
20,Elia Kazan,1948,670454373,False,finalized,3,2/10/15 1:46,"Istanbul, Turkey",1.0000,7-Sep-09,...,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,NaN,NaN,Gentleman's Agreement,NaN,NaN,NaN,NaN
21,John Huston,1949,670454374,True,golden,82,NaN,"Nevada, Mo",1.0000,5-Aug-06,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,5-Aug-06,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN
22,Joseph L. Mankiewicz,1950,670454375,False,finalized,3,2/10/15 3:50,"Wilkes-Barre, Pa",1.0000,11-Feb-09,...,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,NaN,NaN,A Letter to Three Wives,NaN,NaN,NaN,NaN
23,Joseph L. Mankiewicz,1951,670454376,False,finalized,3,2/10/15 1:51,"Wilkes-Barre, Pa",1.0000,11-Feb-09,...,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,NaN,NaN,All About Eve,NaN,NaN,NaN,NaN
24,George Stevens,1952,670454377,False,finalized,3,2/10/15 2:15,"Oakland, Ca",1.0000,18-Dec-04,...,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,NaN,NaN,A Place in the Sun,NaN,NaN,NaN,NaN
25,John Ford,1953,670454378,False,finalized,3,2/10/15 2:15,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Quiet Man,NaN,NaN,NaN,NaN
26,Fred Zinnemann,1954,670454379,False,finalized,3,2/10/15 1:57,"Vienna, Austria",1.0000,29-Apr-07,...,1.0000,Best Director,http://www.nndb.com/people/538/000032442/,NaN,NaN,From Here to Eternity,NaN,NaN,NaN,NaN
27,Elia Kazan,1955,670454380,False,finalized,3,2/10/15 3:50,"Istanbul, Turkey",1.0000,7-Sep-09,...,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,NaN,NaN,On the Waterfront,NaN,NaN,NaN,NaN
28,Delbert Mann,1956,670454381,False,finalized,3,2/10/15 3:53,"Lawrence, Ks",1.0000,30-Jan-20,...,1.0000,Best Director,http://www.nndb.com/people/384/000044252/,NaN,NaN,Marty,NaN,NaN,NaN,NaN
29,George Stevens,1957,670454382,False,finalized,3,2/10/15 3:50,"Oakland, Ca",1.0000,18-Dec-04,...,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,NaN,NaN,Giant,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,Mo'Nique,2010,670454764,True,golden,86,NaN,"Woodlawn, Md",1.0000,11-Dec-67,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,NaN,11-Dec-67,Precious,Black,NaN,NaN,NaN
412,Melissa Leo,2011,670454765,False,finalized,3,2/10/15 1:56,New York City,1.0000,14-Sep-60,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/327/000042201/,NaN,NaN,The Fighter,NaN,NaN,NaN,NaN
413,Octavia Spencer,2012,670454766,False,finalized,3,2/10/15 2:18,"Montgomery, Al",1.0000,25-May-72,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/304/000281458/,NaN,NaN,The Help,NaN,NaN,NaN,NaN
414,Anne Hathaway,2013,670454767,False,finalized,3,2/10/15 2:18,"Brooklyn, Ny",1.0000,12-Nov-82,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/220/000032124/,NaN,NaN,Les MisÌ©rables,NaN,NaN,NaN,NaN
415,Lupita Nyong'o,2014,670454768,False,finalized,3,2/10/15 2:10,"Mexico City, Mexico",1.0000,1-Mar-83,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/570/000380427/,NaN,NaN,12 Years a Slave,NaN,NaN,NaN,NaN
416,Billy Wilder,1961,670927629,False,finalized,3,2/10/15 2:02,"Sucha, Galicia, Austria",1.0000,22-Jun-06,...,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,NaN,NaN,The Apartment,NaN,NaN,NaN,NaN
417,Ginger Rogers,1941,670939613,False,finalized,3,2/10/15 1:53,"Independence, Mo",1.0000,16-Jul-11,...,1.0000,Best Actress,http://www.nndb.com/people/635/000043506/,NaN,NaN,Kitty Foyle,NaN,NaN,NaN,NaN
418,Tom Hanks,1994,670944094,False,finalized,3,2/10/15 2:18,"Concord, Ca",1.0000,9-Jul-56,...,1.0000,Best Actor,http://www.nndb.com/people/687/000022621/,NaN,NaN,Philadelphia,NaN,NaN,NaN,NaN
419,Michael Cimino,1979,670944168,False,finalized,3,2/10/15 3:55,New York City,1.0000,3-Feb-39,...,0.6667,Best Director,http://www.nndb.com/people/810/000043681/,NaN,NaN,The Deer Hunter,NaN,NaN,NaN,NaN
420,Mary Astor,1942,670944316,False,finalized,3,2/10/15 2:05,"Quincy, Il",1.0000,3-May-06,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/690/000042564/,NaN,NaN,The Great Lie,NaN,NaN,NaN,NaN
421,Angelina Jolie,2000,670944478,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,4-Jun-75,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/493/000023424/,NaN,NaN,"Girl, Interrupted",NaN,NaN,NaN,NaN
422,Lee Grant,1976,670944543,False,finalized,3,2/10/15 2:12,New York City,1.0000,31-Oct-27,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/409/000032313/,NaN,NaN,Shampoo,NaN,NaN,NaN,NaN
423,Anne Revere,1946,670944623,False,finalized,3,2/10/15 2:11,New York City,1.0000,25-Jun-1903,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/081/000063889/,NaN,NaN,National Velvet,NaN,NaN,NaN,NaN
424,Faye Dunaway,1977,670944674,False,finalized,3,2/10/15 2:05,"Bascom, Fl",1.0000,14-Jan-41,...,1.0000,Best Actress,http://www.nndb.com/people/884/000022818/,NaN,NaN,Network,NaN,NaN,NaN,NaN
425,Van Heflin,1943,670944755,False,finalized,3,2/10/15 2:04,"Walters, Ok",1.0000,13-Dec-10,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/680/000042554/,NaN,NaN,Johnny Eager,NaN,NaN,NaN,NaN
426,Joanne Woodward,1958,670944822,False,finalized,3,2/10/15 4:14,"Thomasville, Ga",1.0000,27-Feb-30,...,1.0000,Best Actress,http://www.nndb.com/people/747/000043618/,NaN,NaN,The Three Faces of Eve,NaN,NaN,NaN,NaN
427,Gary Cooper,1953,670944835,False,finalized,3,2/10/15 2:08,"Helena, Mt",1.0000,7-May-1901,...,1.0000,Best Actor,http://www.nndb.com/people/740/000031647/,NaN,NaN,High Noon,NaN,NaN,NaN,NaN
428,Elizabeth Taylor,1967,670944920,False,finalized,3,2/10/15 3:58,"London, England",1.0000,27-Feb-32,...,1.0000,Best Actress,http://www.nndb.com/people/624/000023555/,NaN,NaN,Who's Afraid of Virginia Woolf?,NaN,NaN,NaN,NaN
429,Hilary Swank,2005,670944948,False,finalized,3,2/10/15 2:06,"Lincoln, Ne",1.0000,30-Jul-74,...,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,NaN,NaN,Million Dollar Baby,NaN,NaN,NaN,NaN
430,Hilary Swank,2005,670945043,True,golden,86,NaN,"Lincoln, Ne",1.0000,30-Jul-74,...,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,NaN,NaN,Million Dollar Baby,NaN,NaN,NaN,NaN
431,Gwyneth Paltrow,1999,670945693,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,27-Sep-72,...,1.0000,Best Actress,http://www.nndb.com/people/592/000023523/,NaN,NaN,Shakespeare in Love,NaN,NaN,NaN,NaN
432,Jack Albertson,1969,670945790,False,finalized,3,2/10/15 2:08,"Malden, Ma",1.0000,16-Jun-07,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/559/000049412/,NaN,NaN,The Subject Was Roses,NaN,NaN,NaN,NaN
433,Mo'Nique,2010,670945834,False,finalized,3,2/10/15 2:07,"Woodlawn, Md",1.0000,11-Dec-67,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,NaN,NaN,Precious,NaN,NaN,NaN,NaN
434,Marcia Gay Harden,2001,670945895,False,finalized,3,2/10/15 2:13,"La Jolla, Ca",1.0000,14-Aug-59,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/641/000025566/,NaN,NaN,Pollock,NaN,NaN,NaN,NaN
435,Maggie Smith,1970,670946199,False,finalized,3,2/10/15 2:03,"Ilford, Essex, England",1.0000,28-Dec-34,...,1.0000,Best Actress,http://www.nndb.com/people/260/000030170/,NaN,NaN,The Prime of Miss Jean Brodie,NaN,NaN,NaN,NaN
436,Rachel Weisz,2006,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0000,7-Mar-71,...,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,NaN,NaN,NaN,NaN
437,Danny Boyle,2009,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0000,20-Oct-56,...,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,NaN,NaN,NaN,NaN
438,Jason Robards,1977,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0000,26-Jul-22,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,NaN,NaN,NaN,NaN
439,James Coburn,1999,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0000,31-Aug-28,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,NaN,NaN,NaN,NaN
440,John Huston,1949,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0000,5-Aug-06,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN

In [65]:
#Ahora queremos que cuando generemos el índice las columnas persona y year_of_award SIGAN SIENDO COLUMNAS! Que NO se eliminen!
#Esto lo hacemos con drop=False... y ahora veremos esas 2 columnas en nuestro DF

oscars_byID3=oscars.set_index(['person','year_of_award'], drop=False)
oscars_byID3

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                   date_of_birth race_ethnicity  \
person               year_of_award
Lewis Milestone      1927            30-Sep-1895          White
Frank Lloyd          1930             2-Feb-1886          White
Lewis Milestone      1931            30-Sep-1895          White
Norman Taurog        1932            23-Feb-1899          White
Frank Borzage        1933            23-Apr-1894          White
Frank Lloyd          1934             2-Feb-1886          White
Frank Capra          1935            18-May-1897          White
John Ford            1936             1-Feb-1894          White
Frank Capra          1937            18-May-1897          White
Leo McCarey          1938             3-Oct-1898          White
Frank Capra          1939            18-May-1897          White
Victor Fleming       1940            23-Feb-1883          White
John Ford            1941             1-Feb-1894          White
                     1942             1-Feb-1894          White
William Wyler        1943             1-Jul-1902          White
Michael Curtiz       1944            24-Dec-1886          White
Leo McCarey          1945             3-Oct-1898          White
Jerome Robbins       1962              11-Oct-18          White
Billy Wilder         1946              22-Jun-06          White
William Wyler        1947             1-Jul-1902          White
Elia Kazan           1948               7-Sep-09          White
John Huston          1949               5-Aug-06          White
Joseph L. Mankiewicz 1950              11-Feb-09          White
                     1951              11-Feb-09          White
George Stevens       1952              18-Dec-04          White
John Ford            1953             1-Feb-1894          White
Fred Zinnemann       1954              29-Apr-07          White
Elia Kazan           1955               7-Sep-09          White
Delbert Mann         1956              30-Jan-20          White
George Stevens       1957              18-Dec-04          White
...                                          ...            ...
Mo'Nique             2010              11-Dec-67          Black
Melissa Leo          2011              14-Sep-60          White
Octavia Spencer      2012              25-May-72          Black
Anne Hathaway        2013              12-Nov-82          White
Lupita Nyong'o       2014               1-Mar-83          Black
Billy Wilder         1961              22-Jun-06          White
Ginger Rogers        1941              16-Jul-11          White
Tom Hanks            1994               9-Jul-56          White
Michael Cimino       1979               3-Feb-39          White
Mary Astor           1942               3-May-06          White
Angelina Jolie       2000               4-Jun-75          White
Lee Grant            1976              31-Oct-27          White
Anne Revere          1946            25-Jun-1903          White
Faye Dunaway         1977              14-Jan-41          White
Van Heflin           1943              13-Dec-10          White
Joanne Woodward      1958              27-Feb-30          White
Gary Cooper          1953             7-May-1901          White
Elizabeth Taylor     1967              27-Feb-32          White
Hilary Swank         2005              30-Jul-74          White
                     2005              30-Jul-74          White
Gwyneth Paltrow      1999              27-Sep-72          White
Jack Albertson       1969              16-Jun-07          White
Mo'Nique             2010              11-Dec-67          Black
Marcia Gay Harden    2001              14-Aug-59          White
Maggie Smith         1970              28-Dec-34          White
Rachel Weisz         2006               7-Mar-71          White
Danny Boyle          2009              20-Oct-56          White
Jason Robards        1977              26-Jul-22          White
James Coburn         1999              31-Aug-28          White
John Huston          1949               5-Aug-06          White

                                                religion sexual_orientation  \
person               year_of_award
Lewis Milestone      1927                             Na           Straight
Frank Lloyd          1930                             Na           Straight
Lewis Milestone      1931                             Na           Straight
Norman Taurog        1932                             Na           Straight
Frank Borzage        1933                 Roman Catholic           Straight
Frank Lloyd          1934                             Na           Straight
Frank Capra          1935                 Roman Catholic           Straight
John Ford            1936                 Roman Catholic           Bisexual
Frank Capra          1937                 Roman Catholic           Straight
Leo McCarey          1938                             Na           Straight
Frank Capra          1939                 Roman Catholic           Straight
Victor Fleming       1940                             Na           Straight
John Ford            1941                 Roman Catholic           Bisexual
                     1942                 Roman Catholic           Bisexual
William Wyler        1943                             Na           Straight
Michael Curtiz       1944                             Na           Straight
Leo McCarey          1945                             Na           Straight
Jerome Robbins       1962                         Jewish                Gay
Billy Wilder         1946                         Jewish           Straight
William Wyler        1947                             Na           Straight
Elia Kazan           1948                             Na           Straight
John Huston          1949                             Na           Straight
Joseph L. Mankiewicz 1950                         Jewish           Straight
                     1951                         Jewish           Straight
George Stevens       1952                             Na           Straight
John Ford            1953                 Roman Catholic           Bisexual
Fred Zinnemann       1954                         Jewish           Straight
Elia Kazan           1955                             Na           Straight
Delbert Mann         1956                   Presbyterian           Straight
George Stevens       1957                             Na           Straight
...                                                  ...                ...
Mo'Nique             2010                             Na           Straight
Melissa Leo          2011                             Na           Straight
Octavia Spencer      2012                             Na                 Na
Anne Hathaway        2013                      Christian           Straight
Lupita Nyong'o       2014                             Na                 Na
Billy Wilder         1961                         Jewish           Straight
Ginger Rogers        1941              Christian Science           Straight
Tom Hanks            1994           Born-Again Christian           Straight
Michael Cimino       1979                             Na           Straight
Mary Astor           1942                 Roman Catholic           Straight
Angelina Jolie       2000                       Buddhist           Bisexual
Lee Grant            1976                         Jewish           Straight
Anne Revere          1946                             Na           Straight
Faye Dunaway         1977                 Roman Catholic           Straight
Van Heflin           1943                             Na           Straight
Joanne Woodward      1958                             Na           Straight
Gary Cooper          1953                 Roman Catholic           Straight
Elizabeth Taylor     1967                         Jewish           Straight
Hilary Swank         2005                             Na           Straight
                     2005                             Na           Straight
Gwyneth Paltrow      1999                         Jewish           Straight
Jack Albertson       1969                             Na                 Na
Mo'Nique             2010                             Na           Straight
Marcia Gay Harden    2001                             Na           Straight
Maggie Smith         1970                             Na           Straight
Rachel Weisz         2006                         Jewish           Straight
Danny Boyle          2009                 Roman Catholic           Straight
Jason Robards        1977                             Na           Straight
James Coburn         1999                             Na           Straight
John Huston          1949                             Na           Straight

                                    year_of_award                    award  \
person               year_of_award
Lewis Milestone      1927                    1927            Best Director
Frank Lloyd          1930                    1930            Best Director
Lewis Milestone      1931                    1931            Best Director
Norman Taurog        1932                    1932            Best Director
Frank Borzage        1933                    1933            Best Director
Frank Lloyd          1934                    1934            Best Director
Frank Capra          1935                    1935            Best Director
John Ford            1936                    1936            Best Director
Frank Capra          1937                    1937            Best Director
Leo McCarey          1938                    1938            Best Director
Frank Capra          1939                    1939            Best Director
Victor Fleming       1940                    1940            Best Director
John Ford            1941                    1941            Best Director
                     1942                    1942            Best Director
William Wyler        1943                    1943            Best Director
Michael Curtiz       1944                    1944            Best Director
Leo McCarey          1945                    1945            Best Director
Jerome Robbins       1962                    1962            Best Director
Billy Wilder         1946                    1946            Best Director
William Wyler        1947                    1947            Best Director
Elia Kazan           1948                    1948            Best Director
John Huston          1949                    1949            Best Director
Joseph L. Mankiewicz 1950                    1950            Best Director
                     1951                    1951            Best Director
George Stevens       1952                    1952            Best Director
John Ford            1953                    1953            Best Director
Fred Zinnemann       1954                    1954            Best Director
Elia Kazan           1955                    1955            Best Director
Delbert Mann         1956                    1956            Best Director
George Stevens       1957                    1957            Best Director
...                                           ...                      ...
Mo'Nique             2010                    2010  Best Supporting Actress
Melissa Leo          2011                    2011  Best Supporting Actress
Octavia Spencer      2012                    2012  Best Supporting Actress
Anne Hathaway        2013                    2013  Best Supporting Actress
Lupita Nyong'o       2014                    2014  Best Supporting Actress
Billy Wilder         1961                    1961            Best Director
Ginger Rogers        1941                    1941             Best Actress
Tom Hanks            1994                    1994               Best Actor
Michael Cimino       1979                    1979            Best Director
Mary Astor           1942                    1942  Best Supporting Actress
Angelina Jolie       2000                    2000  Best Supporting Actress
Lee Grant            1976                    1976  Best Supporting Actress
Anne Revere          1946                    1946  Best Supporting Actress
Faye Dunaway         1977                    1977             Best Actress
Van Heflin           1943                    1943    Best Supporting Actor
Joanne Woodward      1958                    1958             Best Actress
Gary Cooper          1953                    1953               Best Actor
Elizabeth Taylor     1967                    1967             Best Actress
Hilary Swank         2005                    2005             Best Actress
                     2005                    2005             Best Actress
Gwyneth Paltrow      1999                    1999             Best Actress
Jack Albertson       1969                    1969    Best Supporting Actor
Mo'Nique             2010                    2010  Best Supporting Actress
Marcia Gay Harden    2001                    2001  Best Supporting Actress
Maggie Smith         1970                    1970             Best Actress
Rachel Weisz         2006                    2006  Best Supporting Actress
Danny Boyle          2009                    2009            Best Director
Jason Robards        1977                    1977    Best Supporting Actor
James Coburn         1999                    1999    Best Supporting Actor
John Huston          1949                    1949            Best Director

                                                               movie  \
person               year_of_award
Lewis Milestone      1927                        Two Arabian Knights
Frank Lloyd          1930                            The Divine Lady
Lewis Milestone      1931             All Quiet on the Western Front
Norman Taurog        1932                                     Skippy
Frank Borzage        1933                                   Bad Girl
Frank Lloyd          1934                                  Cavalcade
Frank Capra          1935                      It Happened One Night
John Ford            1936                               The Informer
Frank Capra          1937                     Mr. Deeds Goes to Town
Leo McCarey          1938                            The Awful Truth
Frank Capra          1939                 You Can't Take It with You
Victor Fleming       1940                         Gone with the Wind
John Ford            1941                        The Grapes of Wrath
                     1942                    How Green Was My Valley
William Wyler        1943                               Mrs. Miniver
Michael Curtiz       1944                                 Casablanca
Leo McCarey          1945                               Going My Way
Jerome Robbins       1962                            West Side Story
Billy Wilder         1946                           The Lost Weekend
William Wyler        1947                The Best Years of Our Lives
Elia Kazan           1948                      Gentleman's Agreement
John Huston          1949           The Treasure of the Sierra Madre
Joseph L. Mankiewicz 1950                    A Letter to Three Wives
                     1951                              All About Eve
George Stevens       1952                         A Place in the Sun
John Ford            1953                              The Quiet Man
Fred Zinnemann       1954                      From Here to Eternity
Elia Kazan           1955                          On the Waterfront

## 5-Renombrando filas y columnas

In [71]:
#Esto lo hacemos para hacer nuestro DataFrame más descriptivo y para seguir un "estandar" (por ejemplo usando snake_case o camelCase); y tambien para evitar espacios en blanco y caracteres especiales.

#Volvemos a leer el csv y seteamos los indices como hicimos anteriormente (con person y year_of_award)
oscars_byID2= pd.read_csv('data/Oscars-demographics-DFE.csv', encoding='latin-1', \
                         index_col=['person','year_of_award'])
oscars_byID2

                                     _unit_id  _golden _unit_state  \
person               year_of_award
Lewis Milestone      1927           670454353    False   finalized
Frank Lloyd          1930           670454354    False   finalized
Lewis Milestone      1931           670454355    False   finalized
Norman Taurog        1932           670454356    False   finalized
Frank Borzage        1933           670454357    False   finalized
Frank Lloyd          1934           670454358    False   finalized
Frank Capra          1935           670454359    False   finalized
John Ford            1936           670454360    False   finalized
Frank Capra          1937           670454361    False   finalized
Leo McCarey          1938           670454362    False   finalized
Frank Capra          1939           670454363    False   finalized
Victor Fleming       1940           670454364    False   finalized
John Ford            1941           670454365    False   finalized
                     1942           670454366    False   finalized
William Wyler        1943           670454367    False   finalized
Michael Curtiz       1944           670454368    False   finalized
Leo McCarey          1945           670454369    False   finalized
Jerome Robbins       1962           670454370    False   finalized
Billy Wilder         1946           670454371    False   finalized
William Wyler        1947           670454372    False   finalized
Elia Kazan           1948           670454373    False   finalized
John Huston          1949           670454374     True      golden
Joseph L. Mankiewicz 1950           670454375    False   finalized
                     1951           670454376    False   finalized
George Stevens       1952           670454377    False   finalized
John Ford            1953           670454378    False   finalized
Fred Zinnemann       1954           670454379    False   finalized
Elia Kazan           1955           670454380    False   finalized
Delbert Mann         1956           670454381    False   finalized
George Stevens       1957           670454382    False   finalized
...                                       ...      ...         ...
Mo'Nique             2010           670454764     True      golden
Melissa Leo          2011           670454765    False   finalized
Octavia Spencer      2012           670454766    False   finalized
Anne Hathaway        2013           670454767    False   finalized
Lupita Nyong'o       2014           670454768    False   finalized
Billy Wilder         1961           670927629    False   finalized
Ginger Rogers        1941           670939613    False   finalized
Tom Hanks            1994           670944094    False   finalized
Michael Cimino       1979           670944168    False   finalized
Mary Astor           1942           670944316    False   finalized
Angelina Jolie       2000           670944478    False   finalized
Lee Grant            1976           670944543    False   finalized
Anne Revere          1946           670944623    False   finalized
Faye Dunaway         1977           670944674    False   finalized
Van Heflin           1943           670944755    False   finalized
Joanne Woodward      1958           670944822    False   finalized
Gary Cooper          1953           670944835    False   finalized
Elizabeth Taylor     1967           670944920    False   finalized
Hilary Swank         2005           670944948    False   finalized
                     2005           670945043     True      golden
Gwyneth Paltrow      1999           670945693    False   finalized
Jack Albertson       1969           670945790    False   finalized
Mo'Nique             2010           670945834    False   finalized
Marcia Gay Harden    2001           670945895    False   finalized
Maggie Smith         1970           670946199    False   finalized
Rachel Weisz         2006           670946276    False   finalized
Danny Boyle          2009           670946299    False   finalized
Jason Robards        1977           670964912    False   finalized
James Coburn         1999           670964956    False   finalized
John Huston          1949           670972898    False   finalized

                                    _trusted_judgments _last_judgment_at  \
person               year_of_award
Lewis Milestone      1927                            3      2/10/15 3:45
Frank Lloyd          1930                            3      2/10/15 2:03
Lewis Milestone      1931                            3      2/10/15 2:05
Norman Taurog        1932                            3      2/10/15 2:04
Frank Borzage        1933                            3      2/10/15 1:48
Frank Lloyd          1934                            3      2/10/15 3:50
Frank Capra          1935                            3      2/10/15 2:07
John Ford            1936                            3      2/10/15 1:46
Frank Capra          1937                            3      2/10/15 1:47
Leo McCarey          1938                            3      2/10/15 2:05
Frank Capra          1939                            3      2/10/15 2:04
Victor Fleming       1940                            3      2/10/15 2:10
John Ford            1941                            3      2/10/15 2:12
                     1942                            3      2/10/15 2:02
William Wyler        1943                            3      2/10/15 3:57
Michael Curtiz       1944                            3      2/10/15 2:02
Leo McCarey          1945                            3      2/10/15 2:29
Jerome Robbins       1962                            3      2/10/15 1:55
Billy Wilder         1946                            3      2/10/15 4:02
William Wyler        1947                            3      2/10/15 2:12
Elia Kazan           1948                            3      2/10/15 1:46
John Huston          1949                           82               NaN
Joseph L. Mankiewicz 1950                            3      2/10/15 3:50
                     1951                            3      2/10/15 1:51
George Stevens       1952                            3      2/10/15 2:15
John Ford            1953                            3      2/10/15 2:15
Fred Zinnemann       1954                            3      2/10/15 1:57
Elia Kazan           1955                            3      2/10/15 3:50
Delbert Mann         1956                            3      2/10/15 3:53
George Stevens       1957                            3      2/10/15 3:50
...                                                ...               ...
Mo'Nique             2010                           86               NaN
Melissa Leo          2011                            3      2/10/15 1:56
Octavia Spencer      2012                            3      2/10/15 2:18
Anne Hathaway        2013                            3      2/10/15 2:18
Lupita Nyong'o       2014                            3      2/10/15 2:10
Billy Wilder         1961                            3      2/10/15 2:02
Ginger Rogers        1941                            3      2/10/15 1:53
Tom Hanks            1994                            3      2/10/15 2:18
Michael Cimino       1979                            3      2/10/15 3:55
Mary Astor           1942                            3      2/10/15 2:05
Angelina Jolie       2000                            3      2/10/15 1:49
Lee Grant            1976                            3      2/10/15 2:12
Anne Revere          1946                            3      2/10/15 2:11
Faye Dunaway         1977                            3      2/10/15 2:05
Van Heflin           1943                            3      2/10/15 2:04
Joanne Woodward      1958                            3      2/10/15 4:14
Gary Cooper          1953                            3      2/10/15 2:08
Elizabeth Taylor     1967                            3      2/10/15 3:58
Hilary Swank         2005                            3      2/10/15 2:06
                     2005                           86               NaN
Gwyneth Paltrow      1999                            3      2/10/15 1:49
Jack Albertson       1969                            3      2/10/15 2:08
Mo'Nique             2010                            3      2/10/15 2:07
Marcia Gay Harden    2001                            3      2/10/15 2:13
Maggie Smith         1970                            3      2/10/15 2:03
Rachel Weisz         2006                            3      2/10/15 2:00
Danny Boyle          2009                            3      2/10/15 2:04
Jason Robards        1977                            3      2/10/15 2:03
James Coburn         1999                            3      2/10/15 2:01
John Huston          1949                            3      2/10/15 2:01

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                    birthplace:confidence date_of_birth  \
person               year_of_award
Lewis Milestone      1927                          1.0000   30-Sep-1895
Frank Lloyd          1930                          1.0000    2-Feb-1886
Lewis Milestone      1931                          1.0000   30-Sep-1895
Norman Taurog        1932                          1.0000   23-Feb-1899
Frank Borzage        1933                          1.0000   23-Apr-1894
Frank Lloyd          1934                          1.0000    2-Feb-1886
Frank Capra          1935                          1.0000   18-May-1897
John Ford            1936                          1.0000    1-Feb-1894
Frank Capra          1937                          1.0000   18-May-1897
Leo McCarey          1938                          1.0000    3-Oct-1898
Frank Capra          1939                          1.0000   18-May-1897
Victor Fleming       1940                          1.0000   23-Feb-1883
John Ford            1941                          1.0000    1-Feb-1894
                     1942                          1.0000    1-Feb-1894
William Wyler        1943                          1.0000    1-Jul-1902
Michael Curtiz       1944                          1.0000   24-Dec-1886
Leo McCarey          1945                          1.0000    3-Oct-1898
Jerome Robbins       1962                          1.0000     11-Oct-18
Billy Wilder         1946                          0.6667     22-Jun-06
William Wyler        1947                          1.0000    1-Jul-1902
Elia Kazan           1948                          1.0000      7-Sep-09
John Huston          1949                          1.0000      5-Aug-06
Joseph L. Mankiewicz 1950                          1.0000     11-Feb-09
                     1951                          1.0000     11-Feb-09
George Stevens       1952                          1.0000     18-Dec-04
John Ford            1953                          1.0000    1-Feb-1894
Fred Zinnemann       1954                          1.0000     29-Apr-07
Elia Kazan           1955                          1.0000      7-Sep-09
Delbert Mann         1956                          1.0000     30-Jan-20
George Stevens       1957                          1.0000     18-Dec-04
...                                                   ...           ...
Mo'Nique             2010                          1.0000     11-Dec-67
Melissa Leo          2011                          1.0000     14-Sep-60
Octavia Spencer      2012                          1.0000     25-May-72
Anne Hathaway        2013                          1.0000     12-Nov-82
Lupita Nyong'o       2014                          1.0000      1-Mar-83
Billy Wilder         1961                          1.0000     22-Jun-06
Ginger Rogers        1941                          1.0000     16-Jul-11
Tom Hanks            1994                          1.0000      9-Jul-56
Michael Cimino       1979                          1.0000      3-Feb-39
Mary Astor           1942                          1.0000      3-May-06
Angelina Jolie       2000                          1.0000      4-Jun-75
Lee Grant            1976                          1.0000     31-Oct-27
Anne Revere          1946                          1.0000   25-Jun-1903
Faye Dunaway         1977                          1.0000     14-Jan-41
Van Heflin           1943                          1.0000     13-Dec-10
Joanne Woodward      1958                          1.0000     27-Feb-30
Gary Cooper          1953                          1.0000    7-May-1901
Elizabeth Taylor     1967                          1.0000     27-Feb-32
Hilary Swank         2005                          1.0000     30-Jul-74
                     2005                          1.0000     30-Jul-74
Gwyneth Paltrow      1999                          1.0000     27-Sep-72
Jack Albertson       1969                          1.0000     16-Jun-07
Mo'Nique             2010                          1.0000     11-Dec-67
Marcia Gay Harden    2001                          1.0000     14-Aug-59
Maggie Smith         1970                          1.0000     28-Dec-34
Rachel Weisz         2006                          1.0000      7-Mar-71
Danny Boyle          2009                          1.0000     20-Oct-56
Jason Robards        1977                          1.0000     26-Jul-22
James Coburn         1999                          1.0000     31-Aug-28
John Huston          1949                          1.0000      5-Aug-06

                                    date_of_birth:confidence race_ethnicity  \
person               year_of_award
Lewis Milestone      1927                             1.0000          White
Frank Lloyd          1930                             1.0000          White
Lewis Milestone      1931                             1.0000          White
Norman Taurog        1932                             1.0000          White
Frank Borzage        1933                             1.0000          White
Frank Lloyd          1934                             1.0000          White
Frank Capra          1935                             1.0000          White
John Ford            1936                             1.0000          White
Frank Capra          1937                             1.0000          White
Leo McCarey          1938                             1.0000          White
Frank Capra          1939                             1.0000          White
Victor Fleming       1940                             1.0000          White
John Ford            1941                             1.0000          White
                     1942                             1.0000          White
William Wyler        1943                             1.0000          White
Michael Curtiz       1944                             1.0000          White
Leo McCarey          1945                             1.0000          White
Jerome Robbins       1962                             1.0000          White
Billy Wilder         1946                             1.0000          White
William Wyler        1947                             1.0000          White
Elia Kazan           1948                             1.0000          White
John Huston          1949                             1.0000          White
Joseph L. Mankiewicz 1950                             1.0000          White
                     1951                             1.0000          White
George Stevens       1952                             1.0000          White
John Ford            1953                             1.0000          White
Fred Zinnemann       1954                             1.0000          White

In [77]:
#Ahora modificamos/renombramos Filas --> el primer nombre de person que nos aparece (Lewis Milestone) le ponemos Jimmy Neutron (recordar que este valor es un indice, NO es una data de nuestro DF):
idx_rename={'Lewis Milestone':'Jimmy Neutron'}
#Y ahora modificamos/renombramos Columnas --> las columnas _unit_id y _golden para sacarle los _ y ponerlas en mayuscula:
col_rename={'_unit_id':'Unit_ID','_golden':'Golden'}

#Ahora con la operacion .rename le decimos que haga esos 2 cambios que definimos previamente:
oscars_byID2_renombrados=oscars_byID2.rename(index=idx_rename, columns=col_rename)
oscars_byID2_renombrados

                                      Unit_ID  Golden _unit_state  \
person               year_of_award
Jimmy Neutron        1927           670454353   False   finalized
Frank Lloyd          1930           670454354   False   finalized
Jimmy Neutron        1931           670454355   False   finalized
Norman Taurog        1932           670454356   False   finalized
Frank Borzage        1933           670454357   False   finalized
Frank Lloyd          1934           670454358   False   finalized
Frank Capra          1935           670454359   False   finalized
John Ford            1936           670454360   False   finalized
Frank Capra          1937           670454361   False   finalized
Leo McCarey          1938           670454362   False   finalized
Frank Capra          1939           670454363   False   finalized
Victor Fleming       1940           670454364   False   finalized
John Ford            1941           670454365   False   finalized
                     1942           670454366   False   finalized
William Wyler        1943           670454367   False   finalized
Michael Curtiz       1944           670454368   False   finalized
Leo McCarey          1945           670454369   False   finalized
Jerome Robbins       1962           670454370   False   finalized
Billy Wilder         1946           670454371   False   finalized
William Wyler        1947           670454372   False   finalized
Elia Kazan           1948           670454373   False   finalized
John Huston          1949           670454374    True      golden
Joseph L. Mankiewicz 1950           670454375   False   finalized
                     1951           670454376   False   finalized
George Stevens       1952           670454377   False   finalized
John Ford            1953           670454378   False   finalized
Fred Zinnemann       1954           670454379   False   finalized
Elia Kazan           1955           670454380   False   finalized
Delbert Mann         1956           670454381   False   finalized
George Stevens       1957           670454382   False   finalized
...                                       ...     ...         ...
Mo'Nique             2010           670454764    True      golden
Melissa Leo          2011           670454765   False   finalized
Octavia Spencer      2012           670454766   False   finalized
Anne Hathaway        2013           670454767   False   finalized
Lupita Nyong'o       2014           670454768   False   finalized
Billy Wilder         1961           670927629   False   finalized
Ginger Rogers        1941           670939613   False   finalized
Tom Hanks            1994           670944094   False   finalized
Michael Cimino       1979           670944168   False   finalized
Mary Astor           1942           670944316   False   finalized
Angelina Jolie       2000           670944478   False   finalized
Lee Grant            1976           670944543   False   finalized
Anne Revere          1946           670944623   False   finalized
Faye Dunaway         1977           670944674   False   finalized
Van Heflin           1943           670944755   False   finalized
Joanne Woodward      1958           670944822   False   finalized
Gary Cooper          1953           670944835   False   finalized
Elizabeth Taylor     1967           670944920   False   finalized
Hilary Swank         2005           670944948   False   finalized
                     2005           670945043    True      golden
Gwyneth Paltrow      1999           670945693   False   finalized
Jack Albertson       1969           670945790   False   finalized
Mo'Nique             2010           670945834   False   finalized
Marcia Gay Harden    2001           670945895   False   finalized
Maggie Smith         1970           670946199   False   finalized
Rachel Weisz         2006           670946276   False   finalized
Danny Boyle          2009           670946299   False   finalized
Jason Robards        1977           670964912   False   finalized
James Coburn         1999           670964956   False   finalized
John Huston          1949           670972898   False   finalized

                                    _trusted_judgments _last_judgment_at  \
person               year_of_award
Jimmy Neutron        1927                            3      2/10/15 3:45
Frank Lloyd          1930                            3      2/10/15 2:03
Jimmy Neutron        1931                            3      2/10/15 2:05
Norman Taurog        1932                            3      2/10/15 2:04
Frank Borzage        1933                            3      2/10/15 1:48
Frank Lloyd          1934                            3      2/10/15 3:50
Frank Capra          1935                            3      2/10/15 2:07
John Ford            1936                            3      2/10/15 1:46
Frank Capra          1937                            3      2/10/15 1:47
Leo McCarey          1938                            3      2/10/15 2:05
Frank Capra          1939                            3      2/10/15 2:04
Victor Fleming       1940                            3      2/10/15 2:10
John Ford            1941                            3      2/10/15 2:12
                     1942                            3      2/10/15 2:02
William Wyler        1943                            3      2/10/15 3:57
Michael Curtiz       1944                            3      2/10/15 2:02
Leo McCarey          1945                            3      2/10/15 2:29
Jerome Robbins       1962                            3      2/10/15 1:55
Billy Wilder         1946                            3      2/10/15 4:02
William Wyler        1947                            3      2/10/15 2:12
Elia Kazan           1948                            3      2/10/15 1:46
John Huston          1949                           82               NaN
Joseph L. Mankiewicz 1950                            3      2/10/15 3:50
                     1951                            3      2/10/15 1:51
George Stevens       1952                            3      2/10/15 2:15
John Ford            1953                            3      2/10/15 2:15
Fred Zinnemann       1954                            3      2/10/15 1:57
Elia Kazan           1955                            3      2/10/15 3:50
Delbert Mann         1956                            3      2/10/15 3:53
George Stevens       1957                            3      2/10/15 3:50
...                                                ...               ...
Mo'Nique             2010                           86               NaN
Melissa Leo          2011                            3      2/10/15 1:56
Octavia Spencer      2012                            3      2/10/15 2:18
Anne Hathaway        2013                            3      2/10/15 2:18
Lupita Nyong'o       2014                            3      2/10/15 2:10
Billy Wilder         1961                            3      2/10/15 2:02
Ginger Rogers        1941                            3      2/10/15 1:53
Tom Hanks            1994                            3      2/10/15 2:18
Michael Cimino       1979                            3      2/10/15 3:55
Mary Astor           1942                            3      2/10/15 2:05
Angelina Jolie       2000                            3      2/10/15 1:49
Lee Grant            1976                            3      2/10/15 2:12
Anne Revere          1946                            3      2/10/15 2:11
Faye Dunaway         1977                            3      2/10/15 2:05
Van Heflin           1943                            3      2/10/15 2:04
Joanne Woodward      1958                            3      2/10/15 4:14
Gary Cooper          1953                            3      2/10/15 2:08
Elizabeth Taylor     1967                            3      2/10/15 3:58
Hilary Swank         2005                            3      2/10/15 2:06
                     2005                           86               NaN
Gwyneth Paltrow      1999                            3      2/10/15 1:49
Jack Albertson       1969                            3      2/10/15 2:08
Mo'Nique             2010                            3      2/10/15 2:07
Marcia Gay Harden    2001                            3      2/10/15 2:13
Maggie Smith         1970                            3      2/10/15 2:03
Rachel Weisz         2006                            3      2/10/15 2:00
Danny Boyle          2009                            3      2/10/15 2:04
Jason Robards        1977                            3      2/10/15 2:03
James Coburn         1999                            3      2/10/15 2:01
John Huston          1949                            3      2/10/15 2:01

                                                             birthplace  \
person               year_of_award
Jimmy Neutron        1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Jimmy Neutron        1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                    birthplace:confidence date_of_birth  \
person               year_of_award
Jimmy Neutron        1927                          1.0000   30-Sep-1895
Frank Lloyd          1930                          1.0000    2-Feb-1886
Jimmy Neutron        1931                          1.0000   30-Sep-1895
Norman Taurog        1932                          1.0000   23-Feb-1899
Frank Borzage        1933                          1.0000   23-Apr-1894
Frank Lloyd          1934                          1.0000    2-Feb-1886
Frank Capra          1935                          1.0000   18-May-1897
John Ford            1936                          1.0000    1-Feb-1894
Frank Capra          1937                          1.0000   18-May-1897
Leo McCarey          1938                          1.0000    3-Oct-1898
Frank Capra          1939                          1.0000   18-May-1897
Victor Fleming       1940                          1.0000   23-Feb-1883
John Ford            1941                          1.0000    1-Feb-1894
                     1942                          1.0000    1-Feb-1894
William Wyler        1943                          1.0000    1-Jul-1902
Michael Curtiz       1944                          1.0000   24-Dec-1886
Leo McCarey          1945                          1.0000    3-Oct-1898
Jerome Robbins       1962                          1.0000     11-Oct-18
Billy Wilder         1946                          0.6667     22-Jun-06
William Wyler        1947                          1.0000    1-Jul-1902
Elia Kazan           1948                          1.0000      7-Sep-09
John Huston          1949                          1.0000      5-Aug-06
Joseph L. Mankiewicz 1950                          1.0000     11-Feb-09
                     1951                          1.0000     11-Feb-09
George Stevens       1952                          1.0000     18-Dec-04
John Ford            1953                          1.0000    1-Feb-1894
Fred Zinnemann       1954                          1.0000     29-Apr-07
Elia Kazan           1955                          1.0000      7-Sep-09
Delbert Mann         1956                          1.0000     30-Jan-20
George Stevens       1957                          1.0000     18-Dec-04
...                                                   ...           ...
Mo'Nique             2010                          1.0000     11-Dec-67
Melissa Leo          2011                          1.0000     14-Sep-60
Octavia Spencer      2012                          1.0000     25-May-72
Anne Hathaway        2013                          1.0000     12-Nov-82
Lupita Nyong'o       2014                          1.0000      1-Mar-83
Billy Wilder         1961                          1.0000     22-Jun-06
Ginger Rogers        1941                          1.0000     16-Jul-11
Tom Hanks            1994                          1.0000      9-Jul-56
Michael Cimino       1979                          1.0000      3-Feb-39
Mary Astor           1942                          1.0000      3-May-06
Angelina Jolie       2000                          1.0000      4-Jun-75
Lee Grant            1976                          1.0000     31-Oct-27
Anne Revere          1946                          1.0000   25-Jun-1903
Faye Dunaway         1977                          1.0000     14-Jan-41
Van Heflin           1943                          1.0000     13-Dec-10
Joanne Woodward      1958                          1.0000     27-Feb-30
Gary Cooper          1953                          1.0000    7-May-1901
Elizabeth Taylor     1967                          1.0000     27-Feb-32
Hilary Swank         2005                          1.0000     30-Jul-74
                     2005                          1.0000     30-Jul-74
Gwyneth Paltrow      1999                          1.0000     27-Sep-72
Jack Albertson       1969                          1.0000     16-Jun-07
Mo'Nique             2010                          1.0000     11-Dec-67
Marcia Gay Harden    2001                          1.0000     14-Aug-59
Maggie Smith         1970                          1.0000     28-Dec-34
Rachel Weisz         2006                          1.0000      7-Mar-71
Danny Boyle          2009                          1.0000     20-Oct-56
Jason Robards        1977                          1.0000     26-Jul-22
James Coburn         1999                          1.0000     31-Aug-28
John Huston          1949                          1.0000      5-Aug-06

                                    date_of_birth:confidence race_ethnicity  \
person               year_of_award
Jimmy Neutron        1927                             1.0000          White
Frank Lloyd          1930                             1.0000          White
Jimmy Neutron        1931                             1.0000          White
Norman Taurog        1932                             1.0000          White
Frank Borzage        1933                             1.0000          White
Frank Lloyd          1934                             1.0000          White
Frank Capra          1935                             1.0000          White
John Ford            1936                             1.0000          White
Frank Capra          1937                             1.0000          White
Leo McCarey          1938                             1.0000          White
Frank Capra          1939                             1.0000          White
Victor Fleming       1940                             1.0000          White
John Ford            1941                             1.0000          White
                     1942                             1.0000          White
William Wyler        1943                             1.0000          White
Michael Curtiz       1944                             1.0000          White
Leo McCarey          1945                             1.0000          White
Jerome Robbins       1962                             1.0000          White
Billy Wilder         1946                             1.0000          White
William Wyler        1947                             1.0000          White
Elia Kazan           1948                             1.0000          White
John Huston          1949                             1.0000          White
Joseph L. Mankiewicz 1950                             1.0000          White
                     1951                             1.0000          White
George Stevens       1952                             1.0000          White
John Ford            1953                             1.0000          White
Fred Zinnemann       1954                             1.0000          White
Elia Kazan           1955                             1.0000          White

In [97]:
#Vemos que el nombre "William Wyler" esta repetido... (abajo vemos que se repite en total 3 veces.. osea para 3 años distintos)

#Ahora con loc accedemos a un registro puntual...
oscars_byID2_renombrados.loc[['William Wyler','1947'],:]
#Accedemos a la persona William Wyler y año 1947... y nos vá a listar los elementos asociados a dicha CLAVE COMPUESTA. 
#vER PORQUE ABAJO ME TRAJO TODOS LOS AÑOS, AL PARECER SOLO ME TIENE QUE TRAER LOS DE 1947.

                               Unit_ID  Golden _unit_state  \
person        year_of_award
William Wyler 1943           670454367   False   finalized
              1947           670454372   False   finalized
              1960           670454385   False   finalized

                             _trusted_judgments _last_judgment_at  \
person        year_of_award
William Wyler 1943                            3      2/10/15 3:57
              1947                            3      2/10/15 2:12
              1960                            3      2/10/15 1:55

                                                      birthplace  \
person        year_of_award
William Wyler 1943           Mulhouse, Haut-Rhin, Alsace, France
              1947           Mulhouse, Haut-Rhin, Alsace, France
              1960           Mulhouse, Haut-Rhin, Alsace, France

                             birthplace:confidence date_of_birth  \
person        year_of_award
William Wyler 1943                             1.0    1-Jul-1902
              1947                             1.0    1-Jul-1902
              1960                             1.0    1-Jul-1902

                             date_of_birth:confidence race_ethnicity  \
person        year_of_award
William Wyler 1943                                1.0          White
              1947                                1.0          White
              1960                                1.0          White

                                   ...          year_of_award:confidence  \
person        year_of_award        ...
William Wyler 1943                 ...                               1.0
              1947                 ...                               1.0
              1960                 ...                               1.0

                                     award  \
person        year_of_award
William Wyler 1943           Best Director
              1947           Best Director
              1960           Best Director

                                                                biourl  \
person        year_of_award
William Wyler 1943           http://www.nndb.com/people/463/000032367/
              1947           http://www.nndb.com/people/463/000032367/
              1960           http://www.nndb.com/people/463/000032367/

                            birthplace_gold  date_of_birth_gold  \
person        year_of_award
William Wyler 1943                      NaN                 NaN
              1947                      NaN                 NaN
              1960                      NaN                 NaN

                                                   movie race_ethnicity_gold  \
person        year_of_award
William Wyler 1943                          Mrs. Miniver                 NaN
              1947           The Best Years of Our Lives                 NaN
              1960                               Ben-Hur                 NaN

                            religion_gold sexual_orientation_gold  \
person        year_of_award
William Wyler 1943                    NaN                     NaN
              1947                    NaN                     NaN
              1960                    NaN                     NaN

                            year_of_award_gold
person        year_of_award
William Wyler 1943                         NaN
              1947                         NaN
              1960                         NaN

[3 rows x 25 columns]

In [98]:
#Ahora obtenemos la lista de columnas del DF:
oscars_columns = oscars_byID2_renombrados.columns
oscars_columns

Index(['Unit_ID', 'Golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'birthplace', 'birthplace:confidence',
       'date_of_birth', 'date_of_birth:confidence', 'race_ethnicity',
       'race_ethnicity:confidence', 'religion', 'religion:confidence',
       'sexual_orientation', 'sexual_orientation:confidence',
       'year_of_award:confidence', 'award', 'biourl', 'birthplace_gold',
       'date_of_birth_gold', 'movie', 'race_ethnicity_gold', 'religion_gold',
       'sexual_orientation_gold', 'year_of_award_gold'],
      dtype='object')

In [100]:
#Y ahora la pasamos al tolist() ya que antes (arriba) obtuvimos las columnas y ahora a las mismas las pasamos a una LISTA.
columns_list=oscars_columns.tolist()
columns_list

['Unit_ID',
 'Golden',
 '_unit_state',
 '_trusted_judgments',
 '_last_judgment_at',
 'birthplace',
 'birthplace:confidence',
 'date_of_birth',
 'date_of_birth:confidence',
 'race_ethnicity',
 'race_ethnicity:confidence',
 'religion',
 'religion:confidence',
 'sexual_orientation',
 'sexual_orientation:confidence',
 'year_of_award:confidence',
 'award',
 'biourl',
 'birthplace_gold',
 'date_of_birth_gold',
 'movie',
 'race_ethnicity_gold',
 'religion_gold',
 'sexual_orientation_gold',
 'year_of_award_gold']

In [101]:
#Y ahora al elemento 2 de columns_list (Que era '_unit_state')... ahora lo cambiamos a 'Unit_State':
columns_list[2]='Unit_State'

#Y finalmente lo asignamos la lista nuevamente al DF:
oscars_byID2_renombrados = columns_list
oscars_byID2_renombrados

#Osea que de esta forma tambien podemos renombrar una columna... PISANDO el nombre de una columna (elemento 2 en este caso).
#Igualmente mejor es de la forma anterior, ya que acá nos estamos manejando pos posiciones.

['Unit_ID',
 'Golden',
 'Unit_State',
 '_trusted_judgments',
 '_last_judgment_at',
 'birthplace',
 'birthplace:confidence',
 'date_of_birth',
 'date_of_birth:confidence',
 'race_ethnicity',
 'race_ethnicity:confidence',
 'religion',
 'religion:confidence',
 'sexual_orientation',
 'sexual_orientation:confidence',
 'year_of_award:confidence',
 'award',
 'biourl',
 'birthplace_gold',
 'date_of_birth_gold',
 'movie',
 'race_ethnicity_gold',
 'religion_gold',
 'sexual_orientation_gold',
 'year_of_award_gold']

## 6- Creacion y borrado de columnas

In [147]:
#Definimos nuevamente nuestro DF oscars_shorts:
oscars_short = pd.read_csv('data/Oscars-demographics-DFE.csv',
                        encoding='latin-1',
                        usecols = ['birthplace', 'date_of_birth','race_ethnicity','religion','sexual_orientation','year_of_award','award','movie','person'])
oscars_short.head(5)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

In [148]:
#Ahora le creamos una NUEVA columna asignandole valores a esta (les asignamos todos cero):
oscars_short['last_ten_years']=0 # de esta manera nos crea una columna last_ten_years con todos los valores en 0.
oscars_short.head(5)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person,last_ten_years
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone,0
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd,0
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone,0
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog,0
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage,0

In [149]:
#Ahora vamos a calcular un valor para esta nueva columna:
oscars_short['last_ten_years']=oscars_short['year_of_award']>2000 #Le asignamos el valor de una comparación... si en la columna year_of_award es mayor a 2009,la columna last_ten_years va a valer true y si no cumple esto false.  
oscars_short.tail(5)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person,last_ten_years
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz,True
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle,True
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards,False
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn,False
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston,False

In [150]:
oscars_short['last_ten_years'].value_counts() #Vemos los valores true y false que tiene esa columna.

False    365
True      76
Name: last_ten_years, dtype: int64

In [151]:
#Ahora vamos a BORRAR columnas con DROP...
#Sintaxtis --> DF.drop(columns='columna o columnas separadas por ,',inplace=True) #Inplace=True es para que modifique el DF que le pusimos al principio, sino tendriamos que asignarlo a otro DF o veriamos la salida pero sin modificar el DF. Por esto necesitamos inplace=True si queremos borrar EFECTIVAMENTE la columna.
#Borramos 1 columna (last_ten_years):
oscars_short.drop(columns='last_ten_years',inplace=True)
oscars_short.head(5)
                  
#Ahora borramos 2 columnas a la vez: VER COMOOOO, VER LA SINTAXIS:
#oscars_short.drop(columns=({'year_of_award','last_ten_years'},inplace=True)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

In [153]:
#Ahora si queremos agregar/poner una columna en un lugar especifico.... vamos a querer nuestra nueva columna entre 'date_of_birth' y 'race_ethnicity'....
#Primero vamos a obtener la posición de la columna en la cual queremos agregar (date_of_birth) la nueva columna ('last_ten_years' --> la que antes borramos) -->en el caso de arriba es facil, entre la columna 1 y 2 quisieramos agregar el dato... pero si fueran más columnas se nos complejizaría esto)
#Para obtener la posicion usamos get_loc:
date_of_birth_position=oscars_short.columns.get_loc('date_of_birth')+1 #A esa posicion (1) le sumamos 1 ya que nosotros buscamos agregar una columna DETRAS de esta... entonces le sumamos el 1.
date_of_birth_position #Vemos que está en la posición 2

2

In [156]:
#Ahora con insert agregamos en la posicion date_of_birth_position a nuevamente la columna last_ten_years que tendrá un valor booleano... será True si 'year_of_award'es > a 2000
oscars_short.insert(loc=date_of_birth_position, \
                    column='last_ten_years', \
                    value=(oscars_short['year_of_award']>2000) )
oscars_short.head(5)
#Y asi vemos que se agregó la columna last_ten_years en la posicion 2 después de date_of_birth:

,birthplace,date_of_birth,last_ten_years,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,False,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,False,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,False,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,False,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,False,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

In [157]:
#Y en vez de borrar con drop como ya vimos, podemos usar 'del' y la columna para eliminar la misma.
del oscars_short['last_ten_years'] #Eliminamos la columna que acabamos de crear.
oscars_short.head(5)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

## 7-Operaciones sobre DFs

In [160]:
#Anteriormente vimos que podiamos seleccionar 1 o más columnas sobre un DF...
#Si ahora quisieramos generar un nuevo DF con menos columnas podemos hacer esto:
oscars_basics = oscars_short[['person','movie','award','year_of_award']]#Indicamos el DF y la lista de columnas que queremos seleccionar del mismo.
oscars_basics.head(5)

,person,movie,award,year_of_award
0,Lewis Milestone,Two Arabian Knights,Best Director,1927
1,Frank Lloyd,The Divine Lady,Best Director,1930
2,Lewis Milestone,All Quiet on the Western Front,Best Director,1931
3,Norman Taurog,Skippy,Best Director,1932
4,Frank Borzage,Bad Girl,Best Director,1933

In [162]:
#Aca abajo nos fijamos los tipos de data del DF oscars_short (que tenia 9 columnas)
oscars_short.dtypes.value_counts() #vemos que tiene 8 columnas de tipo object y 1 columna con datos enteros (INT)

object    8
int64     1
dtype: int64

In [164]:
#date_of_birth es de tipo object en oscars_shorts.. 
#la vamos a CONVERTIR a formato fecha (Date):
oscars_short.loc[:,'date_of_birth'] = pd.to_datetime(oscars_short['date_of_birth'],errors = 'coerce')
#Arriba le asignamos a esa columna del df, osea a todo esto -->oscars_short.loc[:,'date_of_birth']
#Le asignamos el resultado de transformar en formato fecha a esa misma columna (osea todo lo que va después del =)

#Y ahora si hacemos un dtypes vamos a ver que tenemos 7 columnas object, 1 date time y 1 int:
oscars_short.dtypes.value_counts()

object            7
int64             1
datetime64[ns]    1
dtype: int64

In [165]:
#Hasta ahora seleccionar columnas utilizando el nombre...
#Ahora vamos a seleccionar columnas dependiendo su dtype. 
#Entonces acá abajo a oscars_shorts le seleccionamos (con select_dtypes())... en "include" le indicamos la lista de formatos que nos interesa (en este caso solo int64)
oscars_shorts_columns_int = oscars_short.select_dtypes(include=['int64'])
#Y hacemos un head para ver el resultado... y vemos que solo nos muestra la columna que tenia formato int64:
oscars_shorts_columns_int.head(5)

   year_of_award
0           1927
1           1930
2           1931
3           1932
4           1933

In [167]:
#Y ahora si queremos seleccionar todas las columnas que tengan formato de número (int o float)... ponemos "number" (ya que number engloba a int y float):
oscars_shorts_columns_number = oscars_short.select_dtypes(include=['number'])
oscars_shorts_columns_number.head(5) #Solo nos muestra 1 columna ya que no tenemos otra int o float.

   year_of_award
0           1927
1           1930
2           1931
3           1932
4           1933

In [168]:
#Tambien podemos seleccionar columnas FILTRANDO en funcion del nombre de las columnas.
#Aca abajo filtramos para que solo aparezcan las columnas que tengan 'birth' en su nombre (esto con filter):
oscars_short_columns_with_birth=oscars_short.filter(like='birth')
oscars_short_columns_with_birth.head(5) #Nos muestran las 2.

           birthplace date_of_birth
0   Chisinau, Moldova    1895-09-30
1   Glasgow, Scotland    1886-02-02
2   Chisinau, Moldova    1895-09-30
3         Chicago, Il    1899-02-23
4  Salt Lake City, Ut    1894-04-23

In [169]:
#Dentro del filter tambien podemos usar expresiones regulares (con regex).
#Abajo buscamos todos los nombres de columnas que tengan un "_"):
oscars_short_columns_with__=oscars_short.filter(regex='\_')
oscars_short_columns_with__.head()

  date_of_birth race_ethnicity sexual_orientation  year_of_award
0    1895-09-30          White           Straight           1927
1    1886-02-02          White           Straight           1930
2    1895-09-30          White           Straight           1931
3    1899-02-23          White           Straight           1932
4    1894-04-23          White           Straight           1933

In [171]:
#Tambien podemos usar filter para filtrar el nombre de la columna exacto (En este caso person):
oscars_shorts_person=oscars_short.filter(items=['person'])
oscars_shorts_person.head(5)

            person
0  Lewis Milestone
1      Frank Lloyd
2  Lewis Milestone
3    Norman Taurog
4    Frank Borzage

In [172]:
#Ahora vamos a ORDENAR COLUMNAS... 
#1ro vemos el orden de las columnas que tenemos en el DF por defecto: 
oscars_short.columns

Index(['birthplace', 'date_of_birth', 'race_ethnicity', 'religion',
       'sexual_orientation', 'year_of_award', 'award', 'movie', 'person'],
      dtype='object')

In [177]:
#Ahora las vamos a reordenar como queremos:
#COPIAMOS la lista de arriba, la pegamos acá abajo (para no tener que escribir todo denuevo) y ponemos 'person' 1ra:
new_col_order = ['person', 'birthplace', 'date_of_birth', 'race_ethnicity', 'religion', 'sexual_orientation', 'year_of_award', 'award', 'movie']

#Ahora especificamos este nuevo orden al DF y lo asignamos a un nuevo DF (oscars_new_col_order):
oscars_new_col_order=oscars_short[new_col_order]
oscars_new_col_order.head()  #Ahora vemos la columna person 1ra.

,person,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie
0,Lewis Milestone,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1927,Best Director,Two Arabian Knights
1,Frank Lloyd,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1930,Best Director,The Divine Lady
2,Lewis Milestone,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1931,Best Director,All Quiet on the Western Front
3,Norman Taurog,"Chicago, Il",1899-02-23,White,Na,Straight,1932,Best Director,Skippy
4,Frank Borzage,"Salt Lake City, Ut",1894-04-23,White,Roman Catholic,Straight,1933,Best Director,Bad Girl

## 8-Selección de Subsets de Datos:

In [3]:
#Vamos a seleccionar:
    #Series de data.
    #Filas del DF.
    #Filas del DF.
    #Columnas simulteneamente.
    #Data con ints y labels.
#Además vamos a ver la "scalar selection"  

#Primero recordamos el DF que estamos utilizando y asi ir comparando con lo que vamos haciendo.
oscars_short = pd.read_csv('data/Oscars-demographics-DFE.csv',
                        encoding='latin-1',
                        usecols = ['birthplace', 'date_of_birth','race_ethnicity','religion','sexual_orientation','year_of_award','award','movie','person'])
oscars_short.head(10)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey

In [4]:
#Con iloc[numero] nos ubicamos en la posición 5 del index y recupera ese dato (arriba vemos que el dato 5 es Glasgow Scotland -para la columna birthplace-):
oscars_short.iloc[5] #Asi, vemos todas las columnas asociadas a la posicion 5.

birthplace            Glasgow, Scotland
date_of_birth                2-Feb-1886
race_ethnicity                    White
religion                             Na
sexual_orientation             Straight
year_of_award                      1934
award                     Best Director
movie                         Cavalcade
person                      Frank Lloyd
Name: 5, dtype: object

In [5]:
#Ahora vamos a ver un rango de datos (con illoc[n1:n2]... donde el n2 NO está incluido en el rango):
oscars_short.iloc[0:6] #Obtenemos del valor 0 al 5 (ya que el 6 NO está incluido)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd

In [6]:
#Tambien podemos indicar de la 5 a la 9 por ej. (ponemos abajo [5:10] ya que el 10 NO se incluye):
oscars_short.iloc[5:10]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey

In [7]:
#Y tambien podemos hacer un step de 2 en 2:
oscars_short.iloc[10:20:2] #desde el 10 hasta el 19 (Ya que el 20 no está incluido), de 2 en 2.

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder

In [8]:
#Además del iloc manejamos el loc... es muy similar pero nos permite hacer MAS cosas:
#Un loc en la posición 5 es LO MISMO que hacer un iloc en la posicion 5... esto lo vemos aca:
oscars_short.iloc[5]  #iloc

birthplace            Glasgow, Scotland
date_of_birth                2-Feb-1886
race_ethnicity                    White
religion                             Na
sexual_orientation             Straight
year_of_award                      1934
award                     Best Director
movie                         Cavalcade
person                      Frank Lloyd
Name: 5, dtype: object

In [9]:
oscars_short.loc[5] #loc, me da lo mismo

birthplace            Glasgow, Scotland
date_of_birth                2-Feb-1886
race_ethnicity                    White
religion                             Na
sexual_orientation             Straight
year_of_award                      1934
award                     Best Director
movie                         Cavalcade
person                      Frank Lloyd
Name: 5, dtype: object

In [10]:
#Con loc e iloc tambien podemos hacer una LISTA de posiciones (por ej. queremos la 5 y la 10):
oscars_short.iloc[[5,10]] #con iloc

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra

In [11]:
oscars_short.loc[[5,10]] #con loc, nos da igual

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra

In [11]:
#Ahora vamos a ver como seleccionar filas y tambien columnas SIMULTANEAMENTE / al mismo tiempo:
#1ro volvemos a ver los datos:
oscars_short.head(10)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey

In [13]:
#Ahora hacemos un iloc para ubicar el dato que esta en la fila 1, columna 5 (osea 1930): 1 al 5:
oscars_short.iloc[1,5] #[fila, col]... recordar que se cuenta desde 0.

1930

In [14]:
#Mostramos un "pedazo" del DF:
oscars_short.iloc[:3,:5] #nos va a mostrar desde la fila 0 a la 2 (NO a la 3 ya que como vimos el 3 no estaria incluido)
                         #y desde la columna 0 a la 4 (ya que el 5 NO esta incluido, osea hasta sexual_orientation)

          birthplace date_of_birth race_ethnicity religion sexual_orientation
0  Chisinau, Moldova   30-Sep-1895          White       Na           Straight
1  Glasgow, Scotland    2-Feb-1886          White       Na           Straight
2  Chisinau, Moldova   30-Sep-1895          White       Na           Straight

In [17]:
#Asi hacemos para poner condiciones solo sobre las columnas (las filas nos mostrarán todos los registros):
all_rows_2_col=oscars_short.iloc[:,[2,5]] #Pongo TODAS las filas y solo la columna 2 y 5.
all_rows_2_col.head(10)

  race_ethnicity  year_of_award
0          White           1927
1          White           1930
2          White           1931
3          White           1932
4          White           1933
5          White           1934
6          White           1935
7          White           1936
8          White           1937
9          White           1938

In [18]:
#Ahora al reves, Asi hacemos para poner condiciones solo sobre las filas (las columnas nos mostrarán todas):
all_rows_2_col=oscars_short.iloc[2:5,:] #Pongo las filas de 2 a 4 (pongo 5 para esto) y TODAS las columnas.
all_rows_2_col.head(10)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

In [20]:
#Habiamos dicho que la diferencia entre iloc y loc era que loc nos permite hacer MAS cosas:
#Por ej. acá enves de estar contando las columnas como hicimos antes --> all_rows_2_col=oscars_short.iloc[:,[2,5]]
#Ahora con el loc podemos indicar lo mismo pero usando el nombre de la columna (Esto es mucho más practico):
all_rows_2_colv2=oscars_short.loc[:,['birthplace','date_of_birth']] #Sobre las filas seguimos sin aplicar ninguna restriccion, solo sobre las columnas. 
all_rows_2_colv2.head(10)

                  birthplace date_of_birth
0          Chisinau, Moldova   30-Sep-1895
1          Glasgow, Scotland    2-Feb-1886
2          Chisinau, Moldova   30-Sep-1895
3                Chicago, Il   23-Feb-1899
4         Salt Lake City, Ut   23-Apr-1894
5          Glasgow, Scotland    2-Feb-1886
6  Bisacquino, Sicily, Italy   18-May-1897
7         Cape Elizabeth, Me    1-Feb-1894
8  Bisacquino, Sicily, Italy   18-May-1897
9            Los Angeles, Ca    3-Oct-1898

In [21]:
#Ahora volvemos a ver los datos:
oscars_short.head(10)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey

In [24]:
#En las filas ponemos la condición que sea de la fila 1 a la 10 pero de 2 en 2 (y sin contar el 10 porque no esta incluido, sino que serian las filas: 1, 3, 5, 7, 9)
#Y sobre las columnas solo la columna 1 (date_of_birth):
oscars_short.iloc[1:10:2,1]

1     2-Feb-1886
3    23-Feb-1899
5     2-Feb-1886
7     1-Feb-1894
9     3-Oct-1898
Name: date_of_birth, dtype: object

In [28]:
#Con loc hacemos lo mismo pero ahora especificamos el nombre de la columna que queremos (ya que con loc como dijimos podemos hacer más cosas que con iloc, por ej. como esto):
oscars_short.loc[1:10:2,'date_of_birth']

1     2-Feb-1886
3    23-Feb-1899
5     2-Feb-1886
7     1-Feb-1894
9     3-Oct-1898
Name: date_of_birth, dtype: object

In [32]:
#Ahora vamos a ver como seleccionar datos USANDO INDICES BOOLEANOS:
#Primero construimos un indice:
oscars_last_20_years=oscars_short['year_of_award']>1999 
#Habiamos visto que si seleccionabamos una columna (arriba seleccionamos year_of_award)... esto nos daria
#una SERIE... y si aplicamos una operación sobre esa columna nos va a dar una serie con el resultado de esa operación.
#Osea que si aplicamos una operación booleana sobre una columna nos va a dar una SERIE booleana que va a tener T o F en función de si cumple o no la condicion que nosotros le estamos poniendo:
#En este caso vamos a armar una serie que se va a llamar oscars_last_20_years y va a tener T si el premio fue otorgado dentro de los ultimos 20 años o  F si fue entregado antes de los 20 años.

In [33]:
oscars_last_20_years

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
411     True
412     True
413     True
414     True
415     True
416    False
417    False
418    False
419    False
420    False
421     True
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429     True
430     True
431    False
432    False
433     True
434     True
435    False
436     True
437     True
438    False
439    False
440    False
Name: year_of_award, Length: 441, dtype: bool

In [39]:
#Si hacemos una suma los True cuentan como 1 y los False como 0....
#Entonces vamos a sacar cuantos oscars fueron entregados en los ultimos 20 años:
oscars_last_20_years.sum() #Sumamos esa serie, osea los T.

82

In [40]:
#Ahora vamos a sacar el PORCENTAJE de premios que se entregaron en los últimos 20 años sobre el TOTAL:
oscars_last_20_years.mean() * 100  #El resultado así nos dá en porcentaje.

18.594104308390023

In [41]:
#Ahora vamos a ver como estan distribuidos los datos (con describe):
oscars_last_20_years.describe()
#Nos dice que tenemos 441 registro de los cuales solo hay 2 valores (porque es T o F) y en su mayoría son False (el top) y que la mayoría del False es de 359 (359 + 82 que me dio antes = 441, los totales)

count       441
unique        2
top       False
freq        359
Name: year_of_award, dtype: object

In [42]:
#Otra forma de ver esto es hacer un value_counts():
oscars_last_20_years.value_counts() #Vemos que tenemos 359 False y 82 True.

False    359
True      82
Name: year_of_award, dtype: int64

In [45]:
#Ahora vamos a hacer lo mismo solo que enves de una columna numerica vamos a usar una columna string.
#Y nos vamos a fijar los premios que contengan 'Best Director' como nombre de premio:
oscars_best_director=oscars_short.award.str.contains('Best Director')
#Hacemos otra serie como antes, tambien booleana. Solo que vamos a poner T si el premio otorgado es 'Best Director' y F si es otro premio.
oscars_best_director

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...
411    False
412    False
413    False
414    False
415    False
416     True
417    False
418    False
419     True
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437     True
438    False
439    False
440     True
Name: award, Length: 441, dtype: bool

In [46]:
#Hacemos un value_counts() y vemos los F y T que tenemos:
oscars_best_director.value_counts()

False    350
True      91
Name: award, dtype: int64

In [47]:
#Estas condiciones que vimos las podemos COMBINAR. Vimos que hicimos:
    #1-Teniamos una serie booleana oscars_last_20_years que nos indicaba si la pelicula era de los ultimos 20 años.
    #2-Teniamos otra serie booleana oscars_best_director que nos indicaba si se trataba del premio a mejor director.
#Entonces decimos abajo cuales son los premios de los ultimos 20 años que fueron para mejor director (por el &):
oscars_last_20_years & oscars_best_director #esto nos devuelve true si cumple con ambas condiciones!

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437     True
438    False
439    False
440    False
Length: 441, dtype: bool

In [49]:
(oscars_last_20_years & oscars_best_director).value_counts() #Vemos los T y F. Vemos que 425 NO cumplen con las 2 condiciones, y los otros 16 SI cumplen (pelis dentro de los ultimos 20 años y entregado a mejor director).
#De esta manera vimos series booleanas para ver si los registros cumplen o no ciertas condiciones.

False    425
True      16
dtype: int64

In [51]:
#Ahora vamos a FILTRAR con esto que vimos de indices booleanos:
#Sobre el DF oscars_short vamos a seleccionar solo los registros que tienen T en la serie oscars_last_20_years
oscars_short[oscars_last_20_years] #Vemos que efectivamente solo nos devuelve los  registros que cumplen que el premio fue entregado en los ultimos 20 años (lo corroboramos viendo la columna year_of_award):

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
41,"St. Louis Park, Mn",29-Nov-54,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Joel Coen
73,"Reading, Berkshire, England",1-Aug-65,White,Na,Straight,2000,Best Director,American Beauty,Sam Mendes
74,"Atlanta, Ga",14-Jan-63,White,Atheist,Straight,2001,Best Director,Traffic,Steven Soderbergh
75,"Duncan, Ok",1-Mar-54,White,Na,Straight,2002,Best Director,A Beautiful Mind,Ron Howard
76,"Paris, France",18-Aug-33,White,See Note,Straight,2003,Best Director,The Pianist,Roman Polanski
77,"Wellington, New Zealand",31-Oct-61,White,Na,Straight,2004,Best Director,The Lord of the Rings: Return of the King,Peter Jackson
78,"San Francisco, Ca",31-May-30,White,Na,Straight,2005,Best Director,Million Dollar Baby,Clint Eastwood
79,"Pingtung, Taiwan",23-Oct-54,Asian,Na,Straight,2006,Best Director,Brokeback Mountain,Ang Lee
80,"Flushing, Ny",17-Nov-42,White,Roman Catholic,Straight,2007,Best Director,The Departed,Martin Scorsese
81,"St. Louis Park, Mn",21-Sep-57,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Ethan Coen
82,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
83,"San Carlos, Ca",27-Nov-51,White,Na,Straight,2009,Best Director,The Hurt Locker,Kathryn Bigelow
84,"London, England",1972,White,Na,Na,2011,Best Director,The King's Speech,Tom Hooper
85,"Paris, France",29-Mar-67,White,Jewish,Straight,2012,Best Director,The Artist,Michel Hazanavicius
86,"Pingtung, Taiwan",23-Oct-54,Asian,Na,Straight,2013,Best Director,Life of Pi,Ang Lee
158,"South Orange, Nj",26-Jul-59,White,Na,Matter of Dispute,2000,Best Actor,American Beauty,Kevin Spacey
159,"Wellington, New Zealand",7-Apr-64,White,Na,Straight,2001,Best Actor,Gladiator,Russell Crowe
160,"Mount Vernon, Ny",28-Dec-54,Black,Protestant,Straight,2002,Best Actor,Training Day,Denzel Washington
161,New York City,14-Apr-73,White,Jewish,Straight,2003,Best Actor,The Pianist,Adrien Brody
162,"Burbank, Ca",17-Aug-60,White,Roman Catholic,Straight,2003,Best Actor,Mystic River,Sean Penn
163,"Terrell, Tx",13-Dec-67,Black,Baptist,Straight,2005,Best Actor,Ray,Jamie Foxx
164,"Fairport, Ny",23-Jul-67,White,Na,Straight,2006,Best Actor,Capote,Philip Seymour Hoffman
165,"Longview, Tx",15-Jul-61,Black,Na,Straight,2007,Best Actor,The Last King of Scotland,Forest Whitaker
166,"London, England",29-Apr-57,White,Na,Straight,2008,Best Actor,There Will Be Blood,Daniel Day-Lewis
167,"Burbank, Ca",17-Aug-60,White,Roman Catholic,Straight,2009,Best Actor,Milk,Sean Penn
168,"Los Angeles, Ca",4-Dec-49,White,Lutheran,Straight,2010,Best Actor,Crazy Heart,Jeff Bridges
169,"Grayshott, Hampshire, England",10-Sep-60,White,Na,Straight,2011,Best Actor,The King's Speech,Colin Firth
170,"Rueil-Malmaison, Hauts-De-Seine, France",19-Jun-72,White,Na,Straight,2012,Best Actor,The Artist,Jean Dujardin
171,"London, England",29-Apr-57,White,Na,Straight,2013,Best Actor,Lincoln,Daniel Day-Lewis
172,"Uvalde, Tx",4-Nov-69,White,Na,Straight,2014,Best Actor,Dallas Buyers Club,Matthew McConaughey
...,...,...,...,...,...,...,...,...,...
330,"Chiswick, London, England",26-Jul-45,White,Na,Straight,2007,Best Actress,The Queen,Helen Mirren
331,"Paris, France",30-Sep-75,White,Na,Straight,2008,Best Actress,The Passionate Life of Edith Piaf,Marion Cotillard
332,"Reading, England",5-Oct-75,White,Na,Straight,2009,Best Actress,The Reader,Kate Winslet
333,"Arlington, Va",26-Jul-64,White,Na,Straight,2010,Best Actress,The Blind Side,Sandra Bullock
334,"Jerusalem, Israel",9-Jun-81,White,Jewish,Straight,2011,Best Actress,Black Swan,Natalie Portman
335,"Summit, Nj",22-Jun-49,White,Na,Straight,2012,Best Actress,The Iron Lady,Meryl Streep
336,"Louisville, Ky",15-Aug-90,White,Na,Na,2013,Best Actress,Silver Linings Playbook,Jennifer Lawrence
337,"Melbourne, Victoria, Australia",14-May-69,White,Na,Straight,2014,Best Actress,Blue Jasmine,Cate Blanchett
401,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
402,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
403,"Catskill Mountains, Ny",12-Dec-70,White,Jewish,Straight,2002,Best Supporting Actress,A Beautiful Mind,Jennifer Connelly
404,"Mumbles, Wales",25-Sep-69,White,Roman Catholic,Straight,2003,Best Supporting Actress,Chicago,Catherine Zeta-Jones
405,"Katy, Tx",25-Apr-69,White,Na,Straight,2004,Best Supporting Actress,Cold Mountain,RenÌ©e Zellweger
406,"Melbourne, Victoria, Australia",14-May-69,White,Na,Straight,2005,Best Supporting Actress,The Aviator,Cate Blanchett
407,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
408,"Chicago, Il",12-Sep-81,Black,Baptist,Straight,2007,Best Supporting Actress,Dreamgirls,Jennifer Hudson
409,"London, England",5-Nov-60,White,Na,Straight,2007,Best Supporting Actress,Michael Clayton,Tilda Swinton
410,"Madrid, Spain",28-Apr-74,Hispanic,Buddhist,Straight,2009,Best Supporting Actress,Vicky Cristina Barcelona,Penelope Cruz
411,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
412,New York City,14-Sep-60,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo
413,"Montgomery, Al",25-May-72,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer
414,"Brooklyn, Ny",12-Nov-82,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway
415,"Mexico City, Mexico",1-Mar-83,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle

In [55]:
(oscars_short[oscars_last_20_years]).describe() #Vemos que tenemos 82 registros (los que nos daban true anteriormente para oscars_last_20_years --> BIEN)

       year_of_award
count      82.000000
mean     2006.731707
std         4.236959
min      2000.000000
25%      2003.000000
50%      2007.000000
75%      2010.000000
max      2014.000000

In [57]:
#Hacemos lo mismo con oscars_best_director:
oscars_short[oscars_best_director] #Comprobamos en "award" que solo esta "Best Director"

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
11,"Pasadena, Ca",23-Feb-1883,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
13,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
15,"Budapest, Hungary",24-Dec-1886,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
17,New York City,11-Oct-18,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler
20,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan
21,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston
22,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz
23,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz
24,"Oakland, Ca",18-Dec-04,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens
25,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford
26,"Vienna, Austria",29-Apr-07,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann
27,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan
28,"Lawrence, Ks",30-Jan-20,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann
29,"Oakland, Ca",18-Dec-04,White,Na,Straight,1957,Best Director,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...
61,"Parma, Emilia-Romagna, Italy",16-Mar-41,White,Na,Straight,1988,Best Director,The Last Emperor,Bernardo Bertolucci
62,"Baltimore, Md",6-Apr-42,White,Jewish,Straight,1989,Best Director,Rain Man,Barry Levinson
63,New York City,15-Sep-46,White,Atheist,Straight,1990,Best Director,Born on the Fourth of July,Oliver Stone
64,"Lynwood, Ca",18-Jan-55,White,Baptist,Straight,1991,Best Director,Dances with Wolves,Kevin Costner
65,"Baldwin, Ny",22-Feb-44,White,Na,Straight,1992,Best Director,The Silence of the Lambs,Jonathan Demme
66,"San Francisco, Ca",31-May-30,White,Na,Straight,1993,Best Director,Unforgiven,Clint Eastwood
67,"Cincinnati, Oh",18-Dec-46,White,Jewish,Straight,1994,Best Director,Schindler's List,Steven Spielberg
68,"Chicago, Il",14-May-52,White,Roman Catholic,Straight,1995,Best Director,Forrest Gump,Robert Zemeckis
69,"Peekskill, Ny",3-Jan-56,White,Roman Catholic,Straight,1996,Best Director,Braveheart,Mel Gibson
70,"Ryde, Isle of Wight, England",6-Jan-54,White,Na,Straight,1997,Best Director,The English Patient,Anthony Minghella
71,"Kapuskasing, Ontario, Canada",16-Aug-54,White,Atheist,Straight,1998,Best Director,Titanic,James Cameron
72,"Cincinnati, Oh",18-Dec-46,White,Jewish,Straight,1999,Best Director,Saving Private Ryan,Steven Spielberg
73,"Reading, Berkshire, England",1-Aug-65,White,Na,Straight,2000,Best Director,American Beauty,Sam Mendes
74,"Atlanta, Ga",14-Jan-63,White,Atheist,Straight,2001,Best Director,Traffic,Steven Soderbergh
75,"Duncan, Ok",1-Mar-54,White,Na,Straight,2002,Best Director,A Beautiful Mind,Ron Howard
76,"Paris, France",18-Aug-33,White,See Note,Straight,2003,Best Director,The Pianist,Roman Polanski
77,"Wellington, New Zealand",31-Oct-61,White,Na,Straight,2004,Best Director,The Lord of the Rings: Return of the King,Peter Jackson
78,"San Francisco, Ca",31-May-30,White,Na,Straight,2005,Best Director,Million Dollar Baby,Clint Eastwood
79,"Pingtung, Taiwan",23-Oct-54,Asian,Na,Straight,2006,Best Director,Brokeback Mountain,Ang Lee
80,"Flushing, Ny",17-Nov-42,White,Roman Catholic,Straight,2007,Best Director,The Departed,Martin Scorsese
81,"St. Louis Park, Mn",21-Sep-57,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Ethan Coen
82,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
83,"San Carlos, Ca",27-Nov-51,White,Na,Straight,2009,Best Director,The Hurt Locker,Kathryn Bigelow
84,"London, England",1972,White,Na,Na,2011,Best Director,The King's Speech,Tom Hooper
85,"Paris, France",29-Mar-67,White,Jewish,Straight,2012,Best Director,The Artist,Michel Hazanavicius
86,"Pingtung, Taiwan",23-Oct-54,Asian,Na,Straight,2013,Best Director,Life of Pi,Ang Lee
416,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder
419,New York City,3-Feb-39,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [59]:
(oscars_short[oscars_best_director]).describe() #Vemos como antes que teniamos 91 T.

       year_of_award
count      91.000000
mean     1971.362637
std        24.679959
min      1927.000000
25%      1950.500000
50%      1970.000000
75%      1992.500000
max      2013.000000

In [60]:
#Ahora combinamos ambas condiciones 
oscars_short[(oscars_last_20_years & oscars_best_director)]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
41,"St. Louis Park, Mn",29-Nov-54,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Joel Coen
73,"Reading, Berkshire, England",1-Aug-65,White,Na,Straight,2000,Best Director,American Beauty,Sam Mendes
74,"Atlanta, Ga",14-Jan-63,White,Atheist,Straight,2001,Best Director,Traffic,Steven Soderbergh
75,"Duncan, Ok",1-Mar-54,White,Na,Straight,2002,Best Director,A Beautiful Mind,Ron Howard
76,"Paris, France",18-Aug-33,White,See Note,Straight,2003,Best Director,The Pianist,Roman Polanski
77,"Wellington, New Zealand",31-Oct-61,White,Na,Straight,2004,Best Director,The Lord of the Rings: Return of the King,Peter Jackson
78,"San Francisco, Ca",31-May-30,White,Na,Straight,2005,Best Director,Million Dollar Baby,Clint Eastwood
79,"Pingtung, Taiwan",23-Oct-54,Asian,Na,Straight,2006,Best Director,Brokeback Mountain,Ang Lee
80,"Flushing, Ny",17-Nov-42,White,Roman Catholic,Straight,2007,Best Director,The Departed,Martin Scorsese
81,"St. Louis Park, Mn",21-Sep-57,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Ethan Coen
82,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
83,"San Carlos, Ca",27-Nov-51,White,Na,Straight,2009,Best Director,The Hurt Locker,Kathryn Bigelow
84,"London, England",1972,White,Na,Na,2011,Best Director,The King's Speech,Tom Hooper
85,"Paris, France",29-Mar-67,White,Jewish,Straight,2012,Best Director,The Artist,Michel Hazanavicius
86,"Pingtung, Taiwan",23-Oct-54,Asian,Na,Straight,2013,Best Director,Life of Pi,Ang Lee
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle

In [63]:
(oscars_short[(oscars_last_20_years & oscars_best_director)]).describe() #Vemos que tenemos 16 que cumplen ambas condiciones, BIEN.

       year_of_award
count      16.000000
mean     2006.687500
std         3.910989
min      2000.000000
25%      2003.750000
50%      2007.500000
75%      2009.000000
max      2013.000000